### ISSUE TITLE
Inject authentication in rootScope instead of every child scope

### ISSUE THREAD

**Issue by sparshy** [meanjs/mean#1047]
Was there a specific reason that we are doing

    $scope.authentication= Authentication 

in every scope, why not just do this once in run with $rootScope??

**Comment by mleanos** [comment]
@sparshy I actually ended up injecting the $state service into my project's $rootScope. It made sense for me since my project started to get big.

For the case of the default MEANJS framework, it probably doesn't make sense for it to implement the Authentication service into the $rootScope, since the front-end is rather small.

If you find that your project is growing in size, and that you'd rather not inject your Authentication service into each controller/scope that needs it, then I don't see anything wrong with injecting it into your $rootScope. If it makes sense for your project.

**Comment by lirantal** [comment]
Closing issue.
