### ISSUE TITLE
Angular interceptor possible dup

### ISSUE THREAD

**Issue by pgrodrigues** [meanjs/mean#1096]
Hey, is there any particular reason to have two similar interceptors in [core/services](https://github.com/meanjs/mean/blob/master/modules/core/client/services/interceptors/auth.interceptor.client.service.js) and in [users/config](https://github.com/meanjs/mean/blob/master/modules/users/client/config/users.client.config.js).

IIRC the first one is the most recent and maybe people forgot to delete the latter or merge in the same file possible changes (only one I can think of is `Authentication.user = null;` which is missing in the first one).

**Comment by mleanos** [comment]
I think you're absolutely right. We don't need both, and the older one was probably overlooked when the authInterceptor service was implemented. I don't see anything that would prevent us from removing the `$http` provider config from the User's module; the `authInterceptor` service is a much better implementation.

We do need to add `Authentication.user = null;` to the service before this line, [authInterceptor service 401](https://github.com/meanjs/mean/blob/master/modules/core/client/services/interceptors/auth.interceptor.client.service.js#L10), and we should be good. This will clear the user out of the browser, so that the lack of authentication is properly represented. 

Related, but not a factor for this issue: We need to address the issue of a `403` status in the interceptor, caused by a request from an unauthenticated user. I think the ACL's will need to be updated to return `401` in these cases.
