### ISSUE TITLE
Deploy MEANJS application to Ubuntu using Nginx as a reverse proxy with SSL

### ISSUE THREAD

**Issue by itleo31** [meanjs/mean#1115]
Hi,

First of all, I want to say thank you all for incredible works. I'm using your meanjs and happy with it. I just has a little confuse when trying to deploy application in my Ubuntu server.

I'm using mean 0.4.1, and start it with production mode in port 8443. And I set up Nginx on port 80, and pass request to 0.0.0.0:8443 (MEAN application). Now I want to use SSL, I see MEANJS has option to configure SSL also, but I see I can configure SSL on Nginx also.

So my question is, can I just configure SSL on Nginx, and disable MeanJS "secure" option on configuration file? Or I have to enable SSL on both Nginx and MeanJS and point to the same key files?

I'm very appriciate if you guy can help me explain this. Thank you agains.

**Comment by lirantal** [comment]
Hi @itleo31 

Thanks for the kind words! Happy you're having fun with it.

Generally speaking, you don't need to work with SSL enabled on both your public facing proxy and the internal application (even though technically you can do that). You don't want to do it due to the fact that you're adding more work on both layers which is un-necessary and only adds complexity and performance issues.

You should probably do the SSL termination on the Nginx server and forward the traffic to your MEAN.js application on port 80.

**Comment by mattbodman** [comment]
Hi @lirantal, I'm coming over to MeanJS from the Python Pyramid world and I will be dealing with this SSL question myself before too long.  In Pyramid, even though Nginx would handle the SSL, I still had to stipulate that the url scheme was HTTPS in the Pyramid config.  Is there a similar config requirement in Node or Express?  If so, where?

**Comment by itleo31** [comment]
Hi @lirantal,

Thank you very much for your kind support. Now I can continue with myself? About this issue, do I need to Close this?

**Comment by lirantal** [comment]
+1
