### ISSUE TITLE
Error: [$rootScope:inprog] $apply already in progress

### ISSUE THREAD

**Issue by rohitkumarvinay** [meanjs/mean#1116]
I am having two checkboxes, on clicking one checkbox executes function on another. while doing so it throws `Error: [$rootScope:inprog] $apply already in progress` error. doing the same on a plunkr works fine though. the [plunk](http://plnkr.co/edit/xjpcDDBK08Sjcvj9Xclv?p=preview).

**Comment by pgrodrigues** [comment]
Use [StackOverflow](http://stackoverflow.com/) for those kind of questions, since your problem is purely AngularJS. Eitherway the answer for your problem is related to [this](http://stackoverflow.com/questions/29008322/apply-already-in-progress-when-sending-a-click-event-to-a-button). Hope that helps :)

**Comment by mg1075** [comment]
The reply and suggestion from @pgrodrigues is right. 
It would be good if this issue is closed.

Also, the plunk you linked to produces the same error.

![image](https://cloud.githubusercontent.com/assets/2031435/11980486/ccf79136-a960-11e5-9ae8-64f651565a7b.png)

**Comment by rohitkumarvinay** [comment]
sorry, just noticed. ignored since the function worked. closing
