### ISSUE TITLE
Allow configurable owasp passwords requirements

### ISSUE THREAD

**Issue by brokyo** [meanjs/mean#1118]
I'm not even sure I have an incredibly strong opinion on this but creating an issue and asking for opinions was [suggested here] (https://groups.google.com/forum/#!topic/meanjs/FxdWbkVb0B4) so I'm going for it :)

I've really enjoyed building stuff out in mean.js but while developing I've found dealing with the password requirements to be a pain. I'm curious about how the community would feel about either making the requirements configurable (enabling developers to change minLength or minOptionalTestsToPass for example) or allowing users to bypass the owasp check altogether. I think it's cool that this enforces security but there's something that sits a bit weirdly with me in taking control away from someone building on top of the framework.

Would love to hear your thoughts!

**Comment by mleanos** [comment]
You can configure the owasp test library, as described here https://github.com/nowsecure/owasp-password-strength-test#configuring

You would need to configure these settings on any instance of the owasp test library; both client-side & server-side. As for making them configurable, it's doable. However, I'm not sure if the framework should be concerned with that over the security of the default application.

In order to make this configurable, using the meanjs config library, we would have to somehow share the server-side configuration with the client-side. We don't have a precedent for that type of implementation yet.

I'm not completely opposed to the idea that you're suggesting, but I doubt it's something that we'd see as a high priority.

**Comment by brokyo** [comment]
Thanks for the feedback. I'm afraid I'm a little confused as jloveland [says here] (https://groups.google.com/d/msg/meanjs/FxdWbkVb0B4/Juf1-Vu4BgAJ) that it's not configurable. Am I just being stupid?

Either way totally understand the value of defaulting to security

**Comment by mleanos** [comment]
@brokyo Jason's comment is correct. However, he's referring to the fact that we didn't provide any out of the box implementation for configuring the owasp-password-strength library within the meanjs framework. You may implement your own custom configuration though, using the library's `config` feature.

**Comment by jloveland** [comment]
Thanks for clarifying @mleanos. I think making the password strength configurable in mean.js is outside the scope of the framework, but the developer can choose the config they want an modify the mean.js tests to reflect the new config.

**Comment by brokyo** [comment]
I apologize for missing your responses entirely. That all sounds good to me and what I was looking for. Seeing as this didn't get any other notice I'll just close it. Appreciate the help
