### ISSUE TITLE
Using REST With meanjs

### ISSUE THREAD

**Issue by sameersanatkpatro** [meanjs/mean#1289]
Hi,
I have a backend implemented in Java and I want to use meanjs in Front end.I want to communicate with  Java backend using REST.Can someone please suggest is there a lib already that can be used using which I can make REST invocation?

Thanks in advance for help.

**Comment by simison** [comment]
MEAN = Mongo+Express+Angular+Node and from those only Angular is frontend.

This project has a very barebone frontend implementation, so I'm not really sure if you're at the right place, but let's see.

What is it that you're exactly looking for? 
- Mobile implementation? Perhaps check react-native.
- Quick and modular way to produce good looking Angular UI? Have a look at [Angular-Material](https://material.angularjs.org/).

>Can someone please suggest is there a lib already that can be used using which I can make REST invocation?

Angular. See e.g. [Angular $resource documentation](https://docs.angularjs.org/api/ngResource/service/$resource) and examples from this repo.

All this said, I think this question is really StackOverflow material rather than in a scope of this repository.

**Comment by sameersanatkpatro** [comment]
Thanks for the info.
