### ISSUE TITLE
Proctecting routes

### ISSUE THREAD

**Issue by nikitpatel24** [meanjs/mean#1301]
Hi,

I started using meanjs recently, Its awesome.
But i can't find a way for protecting the routes.
If the user is logged in and is admin, then only a page should be accessible 
-

**Comment by nikitpatel24** [comment]
down vote
The routes does not seem to be protected, if i create a new route like $stateProvider
.state('dashboard', {
  url: '/d',
  templateUrl: 'modules/core/client/views/dashboard.client.view.html'
})

even though the user is not logged in, he can successfully navigate to the link localhost:3000/d,

how do i restrict this???any ideas?

**Comment by mleanos** [comment]
Look at the Articles client routes. There's `data` property that you can put `roles` into to restrict access. The default behavior (no roles config on your client route) is to have no restrictions.

**Comment by nikitpatel24** [comment]
yes, i saw that , it works perfectly for roles but  when the user is not logged in, he can still navigate to the page by writing the url.

**Comment by mleanos** [comment]
The user should get redirected back to the signin page when they manually type in a route that is restricted to logged in users. In order to secure a route, you must have the `data.roles` defined in the client-side route configuration.

For example, look at the [Chat Routes](https://github.com/meanjs/mean/blob/master/modules/chat/client/config/chat.client.routes.js#L18). If this setting is not present, then non-Authenticated user's have access to the route.

**Comment by nikitpatel24** [comment]
Thank you for your kind help....You are absolutely correct.

**Comment by Wuntenn** [comment]
I'm stuck. I've tried this. However I'm actually trying to protect access to a specific resource. At the moment it's just an SVG however I've taken quite a lot of time and want to only allow authorised users to access it.

Although this does redirect the user to the log in pages as you said. I'm still able to type in the url of the asset directly. Do you know of a solution that would work well. I'm trying to use the acl to protect it but I'm messing up somewhere.
