### ISSUE TITLE
Socket callback throwing error

### ISSUE THREAD

**Issue by aquadestructor** [meanjs/mean#1344]
I am trying to pass a callback function as an acknowledgment through socket.emit but on the event trigger it throws me an error (callback is not a function)

`
 Socket.emit('highFive', 'tobi', function(data){
            console.log(data);
        });
`
`
socket.on('highFive', function (name, cb) {
    
    console.log(name);
    cb('Umair');
  });
`

Error: 

> tobi
Missing error handler on `socket`.
TypeError: cb is not a function
    at Socket.<anonymous> (/Users/C_v/Documents/Teaminate/modules/users/server/sockets/users.server.socket.config.js:35:5)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Socket.onevent (/Users/C_v/Documents/Teaminate/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/Users/C_v/Documents/Teaminate/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/Users/C_v/Documents/Teaminate/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/Users/C_v/Documents/Teaminate/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/Users/C_v/Documents/Teaminate/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/Users/C_v/Documents/Teaminate/node_modules/socket.io/lib/client.js:175:18)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Socket.onPacket (/Users/C_v/Documents/Teaminate/node_modules/engine.io/lib/socket.js:101:14)
    at emitOne (events.js:90:13)
    at WebSocket.emit (events.js:182:7)
    at WebSocket.Transport.onPacket (/Users/C_v/Documents/Teaminate/node_modules/engine.io/lib/transport.js:104:8)
    at WebSocket.Transport.onData (/Users/C_v/Documents/Teaminate/node_modules/engine.io/lib/transport.js:115:8)
    at WebSocket.onData (/Users/C_v/Documents/Teaminate/node_modules/engine.io/lib/transports/websocket.js:76:30)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.ontext (/Users/C_v/Documents/Teaminate/node_modules/ws/lib/WebSocket.js:816:10)
    at /Users/C_v/Documents/Teaminate/node_modules/ws/lib/Receiver.js:477:18
    at /Users/C_v/Documents/Teaminate/node_modules/ws/lib/Receiver.js:361:7

**Comment by Wuntenn** [comment]
@aquadestructor It looks like you're combining the on() and the emit(). They work as a pair so what you should have is the on() which specifies the event handler in the case of a 'highFive' event:

```Socket.on('highFive', function(data){ console.log(data.name); });```

Above I an saying that I want to take the supplied object* and console log it's name property.

```Socket.emit('highFive, { name:'tobi' });```

*Emit only takes two arguements expects an object as the second parameter you get to put anything inside the object that you want against a key (including a function if you wanted). You would use the event handler to act on this this object. Notice 'tobi' is the value for the key 'name'. This should work as I expect you expected! :D

**Comment by aquadestructor** [comment]
@Wuntenn Thank you for the reply. I understand what you specified and I understand how emit and on works. However, the example I posted is from the official docs it is to pass a callback to the emit function for simple acknowledgements.

**Comment by mleanos** [comment]
@aquadestructor The reason you're seeing this exception is because the client-side Socket service does not provide a parameter for a callback to be passed to the Socket.IO server `emit()` method.

Try adding a callback to [this method](https://github.com/meanjs/mean/blob/master/modules/core/client/services/socket.io.client.service.js#L33) of the client-side Socket service. You should end up with something like this:
```javascript
    // Wrap the Socket.io 'emit' method
    function emit(eventName, data, callback) {
      if (service.socket) {
        service.socket.emit(eventName, data, callback);
      }
```

Your above example should work after adding this. The callback will now be passed to the server-side listener. 

Alternatively, you can merely trigger an event from your server-side Socket configuration listener & add a client-side listener for it.

Server-Side Socket configuration
```javascript
socket.on('highFive', function (name) {
  io.emit('acknowledge the high-five', 'acknowledged!');
}
```
Client-Side Controller
```javascript
// Add an event listener to the 'acknowledge the high-five' event
Socket.on('acknowledge the high-five', function (data) {
  console.log(data);
});
```
With this approach you won't have to worry about passing your callback around. However, either way should work out fine for your needs.

**Comment by aquadestructor** [comment]
@mleanos Ah I see now. It was really simple. Thank you so very much for your response. 

@mleanos Are there some good practices when it comes to socket.io? I have read a lot and almost everyone has tried his own implementation. Like for example I am currently using the socket rooms for the implementation in meanjs. Whenever a user signs in he joins a room with his user id and then I use the exact room ids(user ids) to emit to the particular user ids.
 I mean I haven't seen this approach anywhere and I came up with this on my own, and it works great for now. I was previously maintaining a set of socket ids with user ids and then had to remove the id if a user signs out. But is this approach good? Or is there any good approach that one should follow?

**Comment by Wuntenn** [comment]
@mleanos I was wondering why it didn't work. I didn't know about acknowledgements until @aquadestructor said he didn't make a mistake. When I checked the official docs didn't say it was one sided. I didn't even think about the service that we use to wrap the socket.

Shouldn't this change be added to MeanJS? - quite useful

**Comment by aquadestructor** [comment]
@Wuntenn Interesting suggestion. Looking forward to what @mleanos says. I agree this change should be added as it is quite useful, at least in my opinion.

**Comment by mleanos** [comment]
@Wuntenn I don't see any problem adding the `callback` parameter to our client-side Socket service. It shouldn't affect current implementations, and if someone wants to use this functionality they would just need to modify their server-side Socket configuration. However, I am still wondering if it would be better to `emit` an event from the Socket configuration to the client, and have a listener act as your callback. Maybe others could provide input on this.

@aquadestructor As for your implementation of putting each user into their own room.. This is exactly how I handle it on my own application using MEANJS. I use the user's username as the room id, because I don't want to expose user id's from the client-side of my application. All in all, this approach has worked well for me.

**Comment by lirantal** [comment]
Thanks @Wuntenn and @mleanos :+1: 
Closing.
