### ISSUE TITLE
How to set default data before e2e tesing

### ISSUE THREAD

**Issue by avatarr** [meanjs/mean#1369]
Hi, I am encounter with e2e test fail because no data contain in database after server test done. So how to mock-up data into database before e2e start 

Thank in advance

**Comment by ilanbiala** [comment]
@avatarr do you still have this issue? Can you provide more details if so.

**Comment by mleanos** [comment]
I didn't encounter any issues with the E2E tests with the latest *master* branch version. Also, before the E2E tests are ran (using Gulp) the test database is dropped. So there should never be any data in the database when the E2E tests start. 

Furthermore, E2E testing doesn't rely on the server-side functionality; the API requests/responses are mocked. Thus, no data is ever added when these test suites are executed.

Closing, since this doesn't seem relevant to the MEAN framework. @avatarr Feel free to re-open if you feel otherwise.
