### ISSUE TITLE
Use node-email-verification for users

### ISSUE THREAD

**Issue by whitef0x0** [meanjs/mean#1371]
I am the current maintainer of [node-email-verification](https://github.com/whitef0x0/node-email-verification) and would love to see it put to use in the meanjs library. Would the maintainers be open to using this library?

**Comment by whitef0x0** [comment]
@uwolfer

**Comment by lirantal** [comment]
Hey @whitef0x0,

Thanks for the ping.

Could you share more background on your package and what are the benefits in using that over the existing implementation we have? did you go through what we have today in the project?

**Comment by whitef0x0** [comment]
@lirantal it makes it easier and a lot more modular. I'm already using in in my meanjs project.

In your current project you don't seem to have email verification (or double-opt-in as it is usually called). It would make it a lot easier as most modern apps nowadays use something similar to this.

**Comment by lirantal** [comment]
Sounds ok.
Would you be interested in working on a PR for this and write some tests to back it up?

**Comment by whitef0x0** [comment]
@lirantal yep I'd be interested.

**Comment by lirantal** [comment]
@whitef0x0 then what stops you? :)

**Comment by whitef0x0** [comment]
@lirantal I'm starting on it today

**Comment by lirantal** [comment]
Great. A few tips:
1. Once you're at it - please include tests so we know that things work as expected and don't need to suffer through manual flows.
2. I encourage you to create a branch and very quickly submit a PR that you will continue pushing commits to as you go along - it will be easier for us to spot any major changes that you might do along the way, instead of seeing it only when you're done and telling you to refactor the whole thing.

Sounds good?

**Comment by whitef0x0** [comment]
@lirantal I've started work here https://github.com/meanjs/mean/pull/1382

**Comment by lirantal** [comment]
Great, we'll follow up there.

**Comment by lirantal** [comment]
Guess this can be closed now that we have pending work on #1382
