### ISSUE TITLE
I'm having trouble with authorization

### ISSUE THREAD

**Issue by TylerL-uxai** [meanjs/mean#1406]
I've got ACL working but I can't seem to retrieve req.user. There's no user data in the request. How do I fix it?

**Comment by hyperreality** [comment]
Can you show the output of /api/users and /api/users/me when you are logged in?

**Comment by mleanos** [comment]
@TylerL-uxai Where are you trying to retrieve `req.user` from? The server policy script?

Can you verify that the findUserByID method is getting called?

**Comment by TylerL-uxai** [comment]
I'll show you my project, since you probably think it's cool to see what
people are making with your work!
https://blooming-plateau-98618.herokuapp.com/

 And yes, I created the policy script in the management module. I don't
understand how to add userId/articleId to it. Do I just add the app param
to my route and the middleware to the server controller? I feel like there
needs to be something to call the userId function...

I guess it has to happen in the front end? When angular does $http.post or
$save, do I just pass the userid in with it? Not sure if that's the same as
api/users/me

// api/users/me

{"_id":"5788fe46587a1c0b07a04078","displayName":"","provider":"local","__v":0,"created":"2016-07-15T15:16:22.625Z","roles":["user"],"profileImageURL":"modules/users/client/img/profile/default.png","email":"email@gmail.com","lastName":"","firstName":""}


P.S. My "about us" section is definitely going to give Linnovate credit for
the framework. Does it feel right to put Amos Haviv in there? Not really
sure what the story is.

**Comment by hyperreality** [comment]
Are you trying to get user data about the currently logged-in user, or about any given user by their ID?

In users.server.routes.js note the line 
  `app.param('userId', users.userByID);`
which calls the userById function in admin.server.controller.js using the provided Id.

In admin.server.routes.js the following line gets users by their Id:
`  app.route('/api/profile/:userId')` 

admin.server.policy.js ensures that by default only admins can do this. Perhaps the problem you are having here is because your role is only a normal user and you are not allowed access.

The client-side accesses server data through the APIs, so first you need to ensure that the APIs are sending the correct data. /api/users/me appears to be working correctly, so you shouldn't be having problems accessing the currently logged-in user's details.

**Comment by TylerL-uxai** [comment]
Thank you! I'm trying to just restrict access to the logged in user. I
might need to use the userid param , but I can probably do that with
req.body using angular's rootscope.user or whatever mean.js has. What I
need is the logged in user's id. Just like people can't see "create
article" until they log on.

I'm still getting used to your framework but I love it!

**Comment by lirantal** [comment]
Thanks @hyperreality 
Goodluck @TylerL-uxai
