### ISSUE TITLE
How client side retrieve user after authenticated with facebook?

### ISSUE THREAD

**Issue by annvcit** [meanjs/mean#1423]
Hi, 
When authenticated with **facebook**, in **users.authentication.server.controller.js**,
in **oauthCallback** function, it just redirect to client. How client can retrieve user object and display in navigation bar?

Thanks.

**Comment by annvcit** [comment]
Please help me answer this question :smile:

**Comment by Wuntenn** [comment]
Hi @annvcit, This functionality is inside MEANJS already, however if you are asking how it works, it is doing this using [PassportJS](http://passportjs.org/docs).

There is a strategy for each provider When signing in with Facebook the facebook strategy is use: https://github.com/meanjs/mean/tree/master/modules/users/server/config/strategies

The correct strategy is used based on the provider link.

**Comment by annvcit** [comment]
Thanks @Wuntenn. But your answer doesn't satisfy me.
Please take a look at: [users.authentication.server.controller.js line 119](https://github.com/meanjs/mean/blob/master/modules/users/server/controllers/users/users.authentication.server.controller.js#L119)

When the user logged in successfully via Facebook, then in line 119, the response object will redirect to **sessionRedirectURL** or "**/**"

Then if you navigates to homepage, you will see the user's avatar is showed in navigation bar
My question is: How client can retrieves the user object? Because at redirect time, there're no user are passed in `res.redirect(info || sessionRedirectURL || '/'); `

**Comment by NguyenManh94** [comment]
The same to solve problems !

**Comment by Wuntenn** [comment]
Ohh! I understand. I missed a lot of steps above. The short answer is that line 107 is the passport method that signs you in. The part with the redirect is just the callback that you are looking at. By this point we're actually getting info from our database

--- The longer answer (that I tried to avoid):

Best place to start is with the Strategies - Say Facebook: 
https://github.com/meanjs/mean/blob/master/modules/users/server/config/strategies/facebook.js#L39

There's two main parts, the part that were the OAuth call is made to FB which needs the app credentials: https://github.com/meanjs/mean/blob/master/modules/users/server/config/strategies/facebook.js#L12-L17

And the callback function which tells passport what to do with the object that will come back if we successfully get the user details back from FB:https://github.com/meanjs/mean/blob/master/modules/users/server/config/strategies/facebook.js#L19-L53

The providers will have slight variations in the way they format the objects that they return. This is why this problem is well suited to strategies (passportjs). Notice how me grab all the user details that we need including the user photo: https://github.com/meanjs/mean/blob/master/modules/users/server/config/strategies/facebook.js#L32

A username is created by constructing a username from the same details (email) executing a brute-force cycle on the db where the username gets a number appended each time until one is found.

All the strategies have this line in common. It's were we save the providerUserProfile object which has all the stuff we care about. Just for safety we even store all the extra junk that we don't care about: https://github.com/meanjs/mean/blob/master/modules/users/server/config/strategies/facebook.js#L35

Here the save line. 
https://github.com/meanjs/mean/blob/master/modules/users/server/config/strategies/facebook.js#L39

Note that this is a method on the users: https://github.com/meanjs/mean/blob/c95bd7d1cb0c6e651f82b2b4cfa4e937d4dcf154/modules/users/server/controllers/users/users.authentication.server.controller.js

The name of this method is kind of misleading - It could be called something like persistOrLocateUser. This is the part the function that finalises the passport call by returning the saved or previously existing user. Notice now it calls **next** which tells the passport.authentication to carry on (now with the user).


----- Okay with the background flow in place (in your head):
We're able to follow authentication from beginning to end:

1 - user clicks link - (click the facebook one in your head): https://github.com/meanjs/mean/blob/59e6daa63d65798886e446fc7696b6331c9e3aba/modules/users/client/views/authentication/authentication.client.view.html

This means that you pass the parameter **'/api/auth/facebook'** to `'/api/auth/facebook'`. 

2 We see this function here: https://github.com/meanjs/mean/blob/59e6daa63d65798886e446fc7696b6331c9e3aba/modules/users/client/controllers/authentication.client.controller.js#L68

It creates a query string so that it can remember the place that you was trying to navigate to whilst logging you in. Something like `/api/auth/facebook?some%20place%20here&whatever`

It then uses window location to navigate you to that route. So lets lookup the route `/api/auth/facebook`: https://github.com/meanjs/mean/blob/master/modules/users/server/routes/auth.server.routes.js#L23

The routes file says that when we get a request for `api/auth/facebook` handle it by calling
```
users.oauthCall('facebook', {
    scope: ['email']
  })
```
Notice that now we are filling in the details that we want facebook to return once we sign in (this is what the scope does - it says give me these permissions in addition to whatever you would've given me).

So what happens when we call users.oauthCall: https://github.com/meanjs/mean/blob/master/modules/users/server/controllers/users/users.authentication.server.controller.js#L86

This part also pulls the url of the page you was trying to access and stores it in the session.

It uses the first part of the strategy and gets back that user object with all the user details. If you paid attention above you'll remember that the first part of the strategy also looked in the config the the callback url. It calls this url with the facebook-returned-user-object. Remember from the routes: https://github.com/meanjs/mean/blob/master/modules/users/server/routes/auth.server.routes.js#L26that
this is handled by: https://github.com/meanjs/mean/blob/master/modules/users/server/controllers/users/users.authentication.server.controller.js#L101

This resumes the passport authentication process (this time with the user from FB). After checking for errors retrieving the user line 114 uses passports methods to log the user into our system. How?

Given a user object we told passport how to retriever a user from the database.... wtf.... did we?? Yup here in this file I didn't tell you about until now: https://github.com/meanjs/mean/blob/59e6daa63d65798886e446fc7696b6331c9e3aba/modules/users/server/config/users.server.config.js

Given that we saved the user above we log that user in.

---Chapter 3 (how did the user picture get into the navbar?):
When passport signs a user in it attaches the user to the request: http://passportjs.org/docs/authenticate

This means we can collect it like here: https://github.com/meanjs/mean/blob/master/modules/core/server/controllers/core.server.controller.js#L10

We strip it down use the stripped down one as a parameter to swig when we render the main template: https://github.com/meanjs/mean/blob/master/modules/core/server/controllers/core.server.controller.js#L26

This line here uses the param and attaches it to the window: https://github.com/meanjs/mean/blob/master/modules/core/server/views/layout.server.view.html#L48

Later on the Authentication service takes this object and make it available to the app wherever you need it (just include the Authentication service): https://github.com/meanjs/mean/blob/master/modules/users/client/services/authentication.client.service.js

We just so happen to use that same service in the controller responsible for the header.
https://github.com/meanjs/mean/blob/59e6daa63d65798886e446fc7696b6331c9e3aba/modules/core/client/controllers/header.client.controller.js
https://github.com/meanjs/mean/blob/59e6daa63d65798886e446fc7696b6331c9e3aba/modules/core/client/views/header.client.view.html#L35

The end!

**Comment by Wuntenn** [comment]
Sorry I noticed some mistakes and removed them.

**Comment by annvcit** [comment]
What an amazing answer. Thank you so much Mr. Wuntenn

**Comment by Wuntenn** [comment]
NP! 💃 💃 💃
