### ISSUE TITLE
Docker compose failed to build with Hash Sum Mismatch error on Ubuntu

### ISSUE THREAD

**Issue by github-john-doe** [meanjs/mean#1424]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libx/libxmu/libxmuu_1.1.2.2_amd64.deb  Hash Sum Mismatch

**Comment by lirantal** [comment]
@github-john-doe I just recently built and I don't have this issue. @FedeG also built the project using Docker in his proposed PRs and this issue wasn't brought up.

@github-john-doe can you please look it up again and see if it was possibly a local problem on your network end? Otherwise would be good if you can share more details/logs on the problem.
