### ISSUE TITLE
core.client.route-filter

### ISSUE THREAD

**Issue by frkwhiteangel** [meanjs/mean#1518]
im trying to remove the guest state.

`   for (var i = 0, roles = toState.data.roles; i < roles.length; i++) {
          if ((Authentication.user && Authentication.user.roles !== undefined && Authentication.user.roles.indexOf(roles[i]) !== -1)) {
            allowed = false;
            console.log("------------------- truee --------------------------");
            break;
          }
        }`

but none of my console.log is in the console,  and wherever i put 
```
   $state.go('authentication.signin').then(function () {
              // Record previous state
              storePreviousState(toState, toParams);
            });
```

total:

```
    function stateChangeStart(event, toState, toParams, fromState, fromParams) {
      // Check authentication before changing state
      if (toState.data && toState.data.roles && toState.data.roles.length > 0) {
        var allowed = false;

        console.log(toState.data);
        console.log("-------------------------------");
        console.log("TESTING");

        for (var i = 0, roles = toState.data.roles; i < roles.length; i++) {
          if ((Authentication.user && Authentication.user.roles !== undefined && Authentication.user.roles.indexOf(roles[i]) !== -1)) {
            allowed = false;
            console.log("------------------- truee --------------------------");
            break;
          }
        }
        console.log("allowed: " + allowed);

        if (!allowed) {
          event.preventDefault();
          if (Authentication.user !== null && typeof Authentication.user === 'object') {
            $state.transitionTo('forbidden');
          } else {
            console.log("redirecting to login");
            $state.go('authentication.signin').then(function () {
              // Record previous state
              storePreviousState(toState, toParams);
            });
          }
        }
      }
    }

```
it wont show any reflection.

what do i need to do so all non users will be redirected to the signin page?

**Comment by sujeethk** [comment]
Why not simply update the policies for the routes? For server side API set data.roles in the server policies file articles.server.policy.js to have only user and/or admin. And for client side update articles.client.routes.js and core.client.routes.js to set data.roles with only user and/or admin. This should prevent guest access on the API and the client routes and redirect the user to signin page if they hit any of  those pages.

**Comment by frkwhiteangel** [comment]
Because i dont USE the policies cause i couldnt make Them work with post requests

**Comment by mleanos** [comment]
@frkwhiteangel @sujeethk There's a difference in the access granted, for users, between the server-side (ACL policy), and the client-side (route based). The latter is merely used to restrict specific client-side routes based on the User's roles.

@frkwhiteangel In your case, you would need to update your client-side route configurations to include the `{ data: roles: ['user', 'admin'] }` if you want only logged in users to access that route.

See [this Articles route config](https://github.com/meanjs/mean/blob/master/modules/articles/client/config/articles.client.routes.js#L22), which allows all users (including guests) access the the Article list route. And see the [Admin config](https://github.com/meanjs/mean/blob/master/modules/articles/client/config/articles-admin.client.routes.js#L23)

If the `data.roles` config is not present on a state, it inherits from it's parent's settings (if this setting is present in the parent config). Otherwise, it allows all users; the default is to allow access if the configuration is not present.

See: https://github.com/meanjs/mean/blob/master/modules/core/client/config/core.client.route-filter.js#L16

Alternatively, you may change the behavior of the the route-filter to **only** allow access to logged in users, if the setting isn't present. My preference is to just treat all my client-side routes as "open" unless specified otherwise. And the effort it takes to accomplish/maintain this is minimal.

**Comment by frkwhiteangel** [comment]
So by just specifying data there would grant them ? According to the articles config
