### ISSUE TITLE
bad request for non-existent image file

### ISSUE THREAD

**Issue by sujeethk** [meanjs/mean#1537]
Manage social accounts settings page currently does one bad request for a non-existent file.

![image](https://cloud.githubusercontent.com/assets/19917701/19012237/a89cd07a-877d-11e6-987e-8a62b1fbca59.png)

This needs to change on L6 of manage-social-accounts.client.view.html:
`<img ng-src="/modules/users/client/img/buttons/{{vm.user.provider}}.png">`
to:
`<img ng-src="{{vm.user.provider === 'local' ? '' : '/modules/users/client/img/buttons/'+vm.user.provider+'.png'}}">`

**Comment by mleanos** [comment]
I've seen this before. Definitely a bug.

The real issue is the DOM is trying to load this non-existent image because the container is only hidden but still loaded into the DOM.

We should change the condition on [that DIV](https://github.com/meanjs/mean/blob/master/modules/users/client/views/settings/manage-social-accounts.client.view.html#L5) to use `ng-if`:
```html
ng-if="vm.user.provider !== 'local'"
```

**Comment by sujeethk** [comment]
For some reason when i tried ng-if last night it wasn't working. I retried on a fresh copy of master and ng-if now and it works fine. Maybe i was doing something stupid
