### ISSUE TITLE
console.log in controllers

### ISSUE THREAD

**Issue by sujeethk** [meanjs/mean#1541]
Are these console.log in code necessary?

[users.password.server.controller.js#L65](https://github.com/meanjs/mean/blob/master/modules/users/server/controllers/users/users.password.server.controller.js#L65)
[users.password.server.controller.js#L71](https://github.com/meanjs/mean/blob/master/modules/users/server/controllers/users/users.password.server.controller.js#L71)
[articles.client.service.js](https://github.com/meanjs/mean/blob/master/modules/articles/client/services/articles.client.service.js#L50) - harmless yet unnecessary

Especially the one on the password server controller. It is logging the user's password reset link. I would assume it is so that one could test the reset flow even without MSP. But on a production env wouldn't it be a security issue?

**Comment by mleanos** [comment]
I think the one in the Articles client-service can stay. Of course **I would** think that since I'm the one that added that code :) Since we're not handling that error internally to the service, we can output it to the console; it should make debugging/support easier. Ideally, we should handle it in some way but that would most likely vary on the project.

The other console logs you listed can be removed.

**Comment by simison** [comment]
>I think the one in the Articles client-service can stay. Of course I would think that since I'm the one that added that code :) 

Tho it really should be using Angular's ['$log'](https://docs.angularjs.org/api/ng/service/$log) instead of console:
1. `$log` can be set silent from Angular configuration.
2. `console` doesn't work on some weird browsers (it's not part of standard anyway)

First two should definetely be removed, just adds garbage to logs.

**Comment by mleanos** [comment]
@simison Agreed. I know you mentioned the use of `$log` before too. We should make this a standard.
