### ISSUE TITLE
how to temporally disable the cors ? 

### ISSUE THREAD

**Issue by helxsz** [meanjs/mean#1609]
currently I am using the angular- cli to build a web app, which uses the meanjs api, so they are using the local ip address but the two servers are based on two different ports. Because of this, the angular web app receives  _Origin 'http://localhost:4200' is therefore not allowed access._

how would I be able to shortly disable the cors so I can easily test the angular app?

best rgds

**Comment by mleanos** [comment]
You can enable CORS on your destination API. I use this in a couple of my projects: https://github.com/expressjs/cors. Their documentation is really good, and the library's api is easy to use.

You will have to add a `cors` configuration for your express route(s) with a origin of `http://localhost:4200`

**Comment by helxsz** [comment]
```
  var corsOptions = {
    origin: 'http://localhost:4200',
    optionsSuccessStatus: 200 // some legacy browsers (IE11, various SmartTVs) choke on 204
  };
  app.use(cors());
```

which works!!

**Comment by jpca999** [comment]
@helxsz   where in meanjs  app should I add this configuration for cors ?

**Comment by codydaig** [comment]
https://github.com/meanjs/mean/blob/master/config/lib/express.js#L57

**Comment by helxsz** [comment]
@jpca999 as codydaig shows above, in the module.exports.initMiddleware = function (app)

**Comment by jpca999** [comment]
Resolved thx guys! :-)

**Comment by mg1075** [comment]
@helxsz - I think you need to pass `corsOptions` to the `cors()` call, otherwise your option setup is ignored.  https://github.com/expressjs/cors#simple-usage-enable-all-cors-requests
`cors(corsOptions)`

@codydaig - I added the cors package, and added configuration for cors in express, but nothing is changing. 

I can make the the cross origin request call with angular/js/html in a simple, stand-alone page/app, but with node/express, it's not working; I'm getting the error message.

> XMLHttpRequest cannot load &lt;&lt;external url&gt;&gt;. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
