### ISSUE TITLE
 Error in resource configuration for action `query`. Expected response to contain an array but got an object (Request: GET api/properties)

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1617]
yo meanjs 
then,  I created a module by :   yo meanjs:crud-module properties

How to reproduce.... 
so after i login ,  If I do the following :  click the list properties, then click create properties and then list properties links. 
I'll get this error in console.... 

![image](https://cloud.githubusercontent.com/assets/1026325/20081328/ff329f3e-a51c-11e6-8d8d-38121706e18f.png)

![image](https://cloud.githubusercontent.com/assets/1026325/20081342/102898f2-a51d-11e6-9080-c79bff5c1f01.png)

**Comment by dalner** [comment]
I also found this. Seems like the yo generator is out of date with the latest 0.5.0 refactoring of the client service request and client controller.

**Comment by jpca999** [comment]
@dalner dalner +1

**Comment by mleanos** [comment]
@jpca999 This error is indicating that the `query` method of the Angular resource service for your Properties, is returning an object rather than Array. Check your back-end controller method to ensure it's actually returning an array of json objects. Can you provide code examples of what your Properties Angular service & server controller methods look like?

@dalner Can you explain what changes you're referring to, so we can take a look at what might be causing this issue (discrepancy)?

**Comment by dalner** [comment]
@mleanos The yo generator is generating the service and controller logic from v0.4.2 but in the latest v0.5.0 the save logic is in the service and not in the controller (using the createOrUpdate call). I haven't chased down exactly where this error occurs and I believe there is an injection issue along the way but essentially the default articles module differ from the yo generator.
