### ISSUE TITLE
whenver i try to create a module  crud operation  i get the error 

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1618]
http://localhost:3000/properties/create

![image](https://cloud.githubusercontent.com/assets/1026325/20082349/3d73fa8a-a523-11e6-84d0-432568784e21.png)

ALSO  I CAN'T CREATE A NEW ARTICLE 

![image](https://cloud.githubusercontent.com/assets/1026325/20082391/83b5dd06-a523-11e6-84e4-62d136582a4b.png)

**Comment by hyperreality** [comment]
First of all, the create articles page was moved into the admin menu a few months back.

Secondly, if you want to set up a new CRUD module, like you have done with 'Properties', you need to also edit the controller and make a server-side route for it. At the moment it looks like you are trying to GET /articles/create when creating Properties, which is why you are getting a 'Bad Request' error. In the default MEAN you can only POST to /articles/create with the correct fields.

**Comment by jpca999** [comment]
agree...
