### ISSUE TITLE
unable to access the js files.  like underscore.js not loading on browser... 

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1623]
![image](https://cloud.githubusercontent.com/assets/1026325/20159323/f1307e96-a6ad-11e6-9b50-683a77c743a8.png)

![image](https://cloud.githubusercontent.com/assets/1026325/20159243/6a1765e6-a6ad-11e6-9cd7-df783046bb9b.png)

![image](https://cloud.githubusercontent.com/assets/1026325/20159366/2b63bef2-a6ae-11e6-8370-a96b1b8be559.png)

![image](https://cloud.githubusercontent.com/assets/1026325/20159415/70457196-a6ae-11e6-8fe9-29e76049815f.png)

**Comment by mleanos** [comment]
@jpca999 I'm having a hard time following your issue. In the screen shot of the browser window, the error you're getting is a 404 for angular-moment. I see the folder in the other screen shot, but are you sure that `angular-moment.min.js` exists in that folder?

If you can't get your application to load `underscore`, please make sure you're including it in your angular applications [module dependencies](https://github.com/meanjs/mean/blob/master/modules/core/client/app/config.js#L9).

Otherwise, could you be more clear on what your issue is?

**Comment by jpca999** [comment]
@mleanos   none of the additional js files that i add, doesn't load on the browser.

**Comment by mleanos** [comment]
I tested with Underscore and didn't experience what you reported.

I still don't quite follow what the issue is. Like I said before, your screenshots are a little confusing since they don't match up with your description of the error.

![underscore-browser-gh1623](https://cloud.githubusercontent.com/assets/5613734/20161027/af7d13cc-a6a0-11e6-83e3-0cd5b3393821.PNG)

![underscore-default-assetts-gh1623](https://cloud.githubusercontent.com/assets/5613734/20161030/b3b696a2-a6a0-11e6-916f-d80a0ffd5ab9.PNG)

**Comment by jpca999** [comment]
wow - i dont understand how its not letting me see the js files.   
btw did you use docker-compose up   to serve ?

**Comment by jpca999** [comment]
got it, fu@#in issue was with the trailing spaces.

**Comment by mleanos** [comment]
Why did you reopen this issue? It appeared yhat you resolved your problem.

**Comment by jpca999** [comment]
@mleanos   yes, sorry about that,,    Can you please suggest a solution for this one ?https://github.com/meanjs/mean/issues/1626
