### ISSUE TITLE
What is the best way to debug Express controller

### ISSUE THREAD

**Issue by avatarr** [meanjs/mean#1678]
I'm looking for node debugger of Express controller or model easy to use. If someone who has experience with Rials just type 'binding.pry' a process will stop at a line of code and you can typing in terminal to log variable or data ai current process or state. Dose anyone have a best tool for debug controller

**Comment by jpca999** [comment]
I've been using console log to log   req,res objects but there should be better way.

**Comment by vaucouleur** [comment]
@avatarr @jpca999 http://stackoverflow.com/questions/1911015/how-do-i-debug-node-js-applications

**Comment by dalelotts** [comment]
You can also use tools that support the Chome debugging protocol - https://youtu.be/KxRX_HRGRo4?t=19m1s

**Comment by Wuntenn** [comment]
If you use an IDE like VSCode, Webstorm, or Sublime, you'll get built-in tools that will help you with the server-side debugging.

If on the other hand you prefer to use alternative IDE's/editors then you may want to look at:

- Chrome Devtools: Giving you the powers to debug from inside your browser
  see: [Article by Paul Irish](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.lrmvme1h1) - U'll just have to change one line in the `gulpfile` to make this work!! This works with the latest version of Chrome, although for a (long) time it wasn't working which is why it's good to know about:

- Dev Tool: Giving you the power of Chrome debug inside an electron ~~spell~~ shell
  see: https://github.com/Jam3/devtool

Iron-node and node-inspector are both deprecated

**Comment by lirantal** [comment]
Use your IDE or if you're using Node v7 you can just run it with --inspect and load a specially generated link on chrome.

MEAN.JS has it as the default when you 'npm start' and will generate that link for you.
