### ISSUE TITLE
Feature request: Support multiple frontends

### ISSUE THREAD

**Issue by kybarg** [meanjs/mean#1703]
I have separated admin and clients area at my project. I've made changes to many files.
It would be nice if MEAN.js supported this feature by default, so gulp task worked for them too.
For example:
`modules/**/client/[FRONTEND NAME]/**`

**Comment by lirantal** [comment]
That would be really be too complex to implement at the moment if you mean an entirely new frontend stack (i.e: react, vue2 etc). But I'm trying to resolve this with a new architecture at https://github.com/lirantal/Riess.js which will hopefully end up being MEAN.JS 2.

**Comment by kybarg** [comment]
@lirantal It's not too complex. This structure can support unlimited frontends. I have implemented it in my project but now it has two hardcoded frontends. I can make fork or branch but yo generator won't work with it well.

**Comment by lirantal** [comment]
Great so you're welcome to elaborate on it :)

On Jan 19, 2017 15:38, "Ruslan Kyba" <notifications@github.com> wrote:

@lirantal <https://github.com/lirantal> It's not too complex. This
structure can support rt unlimited frontends. I have implemented it in my
project but now it has two hardcoded frontends. I can make fork or branch
but yo generator won't work with it well.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/meanjs/mean/issues/1703#issuecomment-273778102>, or mute
the thread

**Comment by mleanos** [comment]
@kybarg How do you serve up each instance of your frontends? Sounds like they are all running through the server-side template engine; you haven't changed any server-side? Your use case makes sense for providing a different UI for mobile vs desktop. However, I don't see this type of feature adding benefit for the MEANJS project, due to it's complexity. Furthermore, as Liran pointed out, we may soon have MEANJS 2 that has a completely decoupled back-end & front-end.

**Comment by kybarg** [comment]
@mleanos On server side i have only separate `index` templates for `/*` and `/admin*` routes.

**Comment by simison** [comment]
I'll close this in favor of #1849

Let's try to first separate current frontend from our backend. After that it's relevant to discuss other possible frontend(s).
