### ISSUE TITLE
meanjs, crud module, error listing

### ISSUE THREAD

**Issue by pjindent** [meanjs/mean#1704]
With meanjs 0.4.2 and yo generated CRUD code for "customer", the /customers list view fails, however a view page with specific id is working, /customers/:id.

Here is the error I get: Error: [$resource:badcfg] Error in resource configuration for action `get`. Expected response to contain an object but got an array. angular.js:11706.

**Comment by mleanos** [comment]
@pjindent Can you share your Customer module's client-side route configuration?

It sounds like the /customers list route is using an incorrect configuration that is requesting the `/api/customers/:customerId` endpoint. Otherwise, the issue is probably on the server-side, where your endpoint is returning a single Customer & not an array. I'd check that as well.

**Comment by pjindent** [comment]
the server-side controller looks fine, it should return two documents:
exports.list = function(req, res) {
  Customer.find().sort('-created').populate('user', 'displayName').exec(function(err, customers) {
    if (err) {
      return res.status(400).send({
        message: errorHandler.getErrorMessage(err)
      });
    } else {
      res.jsonp(customers);
    }
  });
};

**Comment by pjindent** [comment]
In the else, I added a console.log("***** Customers" + JSON.stringify(customers)); and I get (I have changed the data and removed some of the fields):

Customers[{"_id":"58xxxx","user":{"_id":"53xxxxx","displayName":"XX"},"__v":0,"created":"2017-01-22T19:28:38.068Z"},{"_id":"58xxxxx","user":{"_id":"58xxxxxx","displayName":"XX"},"__v":0,"created":"2017-01-21T05:00:04.999Z"}]

**Comment by mleanos** [comment]
@pjindent I apologize, I incorrectly read the error you reported as the the Angular resource service expecting an array. However, after looking back at it, I realized the $resource service is expecting an **object**, not *array*.

It does appear that your server-side controller method is correct. You should be returning an array from your `customers.list` method. The problem seems to be on the client-side. It's most likely a simple Angular ui-router configuration mistake.

Can you share your Customer's client-side routes configuration? Again, I apologize for the confusion on my part. I sent you on a wild goose chase on the backend.

**Comment by pjindent** [comment]
Please replace "products" with "Customers"
Routes are configured like this:
function routeConfig($stateProvider) {
    $stateProvider
      .state('products', {
        abstract: true,
        url: '/products',
        template: '<ui-view/>'
      })
      .state('products.list', {
        url: '',
        templateUrl: 'modules/products/client/views/list-products.client.view.html',
        controller: 'ProductsListController',
        controllerAs: 'vm',
        data: {
          pageTitle: 'Products List'
        }
      })

------------------
Controller is:
(function () {
  'use strict';

  angular
    .module('products')
    .controller('ProductsListController', ProductsListController);

  ProductsListController.$inject = ['ProductsService'];

  function ProductsListController(ProductsService) {
    var vm = this;

    vm.products = ProductsService.query();
  }
}());

-----------------------------
function ProductsController ($scope, $state, $window, Authentication, product) {
    var vm = this;

    vm.authentication = Authentication;
    vm.product = product;
    vm.error = null;
    vm.form = {};
    vm.remove = remove;
    vm.save = save;

------------------------------
// Products service used to communicate Products REST endpoints
(function () {
  'use strict';

  angular
    .module('products')
    .factory('ProductsService', ProductsService);

  ProductsService.$inject = ['$resource'];

  function ProductsService($resource) {
    return $resource('api/products/:productId', {
      productId: '@_id'
    }, {
      update: {
        method: 'PUT'
      }
    });
  }
}());

**Comment by mleanos** [comment]
This client-side code looks good to me. I don't see any issues. What does your server-side routes file look for Products?

Somewhere you are returning a single object, rather than an array when a GET request on `/api/products` is requested. Just make sure that your route handler for that endpoint is actually returning an array.

Also, from your previous example, you're using `res.jsonp()` to return the data from the request. We've moved to using `res.json()`. I don't see why that would cause your issue, but it could be something to change regardless.

**Comment by pjindent** [comment]
The server-side routes are:
`var productsPolicy = require('../policies/products.server.policy'),
  products = require('../controllers/products.server.controller');

module.exports = function(app) {
  // Products Routes
  app.route('/api/products').all(productsPolicy.isAllowed)
    .get(products.list)
    .post(products.create);

  app.route('/api/products/:productId').all(productsPolicy.isAllowed)
    .get(products.read)
    .put(products.update)
    .delete(products.delete);

  // Finish by binding the Product middleware
  app.param('productId', products.productByID);
};
`

**Comment by mleanos** [comment]
I really don't see any issues with the code you shared. Seems like something weird is going on with your `ProductsService.query()` method. From my understanding, unless you explicitly configure it otherwise, the `.query()` method of the Angular $resource service should **always** expect an array.

You could try adding the following to your ProductsService configuration..
```javascript
update: {
  method: 'PUT'
},
query: {
  isArray: true
}
```

**Comment by lirantal** [comment]
-
