### ISSUE TITLE
Mean.js in a vagrant?

### ISSUE THREAD

**Issue by haluvibe** [meanjs/mean#173]
Love the Mean.js project. I did however have a lot of problems getting it setup on a vagrant box. 

I wanted to request that you have on your website the possibility to download a fully configured vagrant file and a set of clear, instructions on installing pre-requisites and how to get to the part of your tutorial where you first use the 'grunt' command.

I trust this would save alot of frustration for people like me who are using the meanjs as a starting point to learn MEAN development.

**Comment by Larraby** [comment]
Why have you closed it? Maybe someone in the community experienced with vagrant & ubuntu & mean would make one.
Both are closed by now, and a quick search gives you no quick straight-to-the-code options unfortunately. Have tried about 4 diffrent MEAN vagrant configs already haven't managed to run them without tweaks

**Comment by jloveland** [comment]
Why not just use the docker image. What's the use case for vagrant now that we have docker? Is Vagrant better for development purposes?

**Comment by lirantal** [comment]
@Larraby also a quick search yields quite a few MEAN based vagrants:
https://github.com/cmoudy/mean-vagrant
https://coderwall.com/p/iv-rfg/instalation-mean-stack-mongodb-express-angular-node-js-on-vagrant

and even a specific MEAN.js one:
https://atlas.hashicorp.com/arvindr21/boxes/mean-box

**Comment by Larraby** [comment]
Thanks for answer!

In case someone googles this thread and goes with this box:
https://atlas.hashicorp.com/arvindr21/boxes/mean-box
If you have problems with permissions you have to dig to comments in an article and recreate a .npm folder. I had problems with localhost:3000, but that's probably because of my local machine.

Wish MEAN stack would be as easy and accessible on Windows as PHP with XAMPP one day
