### ISSUE TITLE
How to reflect updated Changes on UI instantaneously. 

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1757]
I have a trello like UI / app with list of tasks to be done. Same list is opened by another user. 

If I change the underlying mondo object at one place it should instantaneously reflect the change in another view/ browser:

What technologies I need for this ? 
Socketio, redis. What else ?

I know it's not directly linked with meanjs but I love this community & they might have resolved this in the way it works well with meanjs backend.

**Comment by lirantal** [comment]
Socket.io and sounds like a job for RethinkDB's real time changes.

@jpca999 we welcome community members to share and post but the GitHub project should be used for mean.js library related issues. For any other general questions or even questions surrounding mean.js you should probably leverage stackoverflow or such. It's hard otherwise to keep track of the issue queue for the project.

**Comment by jpca999** [comment]
got you, appreciate it @lirantal    So if I use ReThinkDb, I dont have to use Redis ?

**Comment by lirantal** [comment]
RethinkDB has the real-time support builtin already.
Otherwise some kind of polling Mongo + Socket.io should do the trick.

**Comment by PierreBrisorgueil** [comment]
Hey, done with Mongo + Socket.io on our side, go feedback for the moment, no problems. 

Never try ReThinkDb for the moment.

**Comment by jpca999** [comment]
I appreciate it. 

J
