### ISSUE TITLE
Can not found api

### ISSUE THREAD

**Issue by GinVlad** [meanjs/mean#1799]
Hello, i used command `yo meanjs:crud-module` to create **articles** CRUD. But when i click to create post, meanjs can not found link `POST http://localhost:3000/articles/api/articles 404 (Not Found)`

And how to render html data with meanjs

**Comment by billyjov** [comment]
@GinVlad you choose the wrong link to find the *api*. 

as i can see here [articles/server/routes](https://github.com/meanjs/mean/blob/master/modules/articles/server/routes/articles.server.routes.js#L16)

you need following url instead `http://localhost:3000/api/articles/`

**Comment by mleanos** [comment]
@billyjov Is correct.

The MEANJS Generator is out of syc with the current *master* branch. We moved away from using a `<base>` tag in our Layout template. See https://github.com/meanjs/mean/pull/1544

@GinVlad In order to fix this issue you will need to prefix your API end-points from your client-side services with a `/`. See the [articles service](https://github.com/meanjs/mean/blob/master/modules/articles/client/services/articles.client.service.js#L11). There may be other instances where you need to add the "/" to. The above mentioned PR should be a good guide to reconcile the differences.

Unfortunately, the generator project isn't well maintained at this point. Any help in that regard would be much appreciated. As it stands the best way to create a new CRUD module would be to copy the *modules/articles* folder from a project that was cloned from *master*.

**Comment by GinVlad** [comment]
Thank you, it worked :)

**Comment by GinVlad** [comment]
I tried install angular-sanitize but can not work. Then i upgrade angular to 1.6.4 and when reload page, it render to blank page with error. How to install angular-sanitize to MEANJS ?
