### ISSUE TITLE
Template cache in production build?

### ISSUE THREAD

**Issue by kitce** [meanjs/mean#1820]
I am using 0.5.0.

I found that all of my `/modules/*/client/views/*.html` are put into a service named `$templateCache` in the production build `application-xxx.min.js`.

I checked the browser inspector, the browser will still makes new request when I trigger to display a HTML template, e.g. a modal.

I am wondering what `$templateCache` is used for, why do I need to include all the HTML files in the `application-xxx.min.js` while the application will only fetch the HTML when it is needed.

**Comment by simison** [comment]
If I remember correct  — how it works is that in template cache you should have template by key (i.e. in this case path is the key), and if it's not there, Angular goes and fetches it from the server (again from that same path).

So Angular looks by key `/folder/template.html` from `$templateCache` uses it if it finds it. If it doesn't it loads the file from path `/folder/template.html`.

So if the system doesn't work, I assume that the key/path in `ng-template="'`/folder/template.html`'"` doesn't match to the one in `$templateCache`.

**Comment by kitce** [comment]
That's what I am confused about.

When I load a page, the browser makes a network request to fetch the HTML file, e.g. `nav.client.view.html`, but it is already in `$templateCache` as I can see `$templateCache.put("nav.client.view.html",'<nav><nav/>')` in the `.min.js`

**Comment by simison** [comment]
And I just want to confirm you have this somewhere, right?
```
ng-include="'nav.client.view.html'"
```

and not for example:
```
ng-include="'/modules/some-path/nav.client.view.html'"
```

**Comment by kitce** [comment]
My example maybe bad.

Let's clarify that, in `/modules/core/server/views/layout.html`, I have :
`<ng-include src="'/modules/core/client/views/nav.client.view.html'"></ng-include>`

In `application-xxx.min.js`, I have :
`$templateCache.put("modules/core/client/views/nav.client.view.html",'...some markup...')`

Notice that the file path being put into `$templateCache` is different, is that the reason why the browser makes new request for every HTML file?

**Comment by simison** [comment]
>Notice that the file path being put into `$templateCache` is different, is that the reason why the browser makes new request for every HTML file?

Exactly, that's my guess.

Wanna try and modify this line:
```js
templateBody: '		$templateCache.put(\'<%= url %>\', \'<%= contents %>\');',
```

...from [gulpfile](https://github.com/meanjs/mean/blob/master/gulpfile.js#L272) to:
```js
templateBody: '		$templateCache.put(\'/<%= url %>\', \'<%= contents %>\');',
```

...and run the build again to see if that helps? So just add that `/` before url.

**Comment by kitce** [comment]
Thanks for the hint, it works!

I end up changing this line :
https://github.com/meanjs/mean/blob/master/gulpfile.js#L269
`root : '/modules/',`

And the original `build` task does not include `templatecache` task, so if I only need to build the script instead of running `gulp start:prod` in production, I have to change https://github.com/meanjs/mean/blob/master/gulpfile.js#L412 into :
`runSequence('templatecache', 'env:dev', 'wiredep:prod', 'lint', ['uglify', 'cssmin'], done);`

But now I only changed line 269 and run `gulp start:prod` on production server, and everything seems good, the application will not read the HTML from `$templateCache` instead of making new request.

**Comment by simison** [comment]
Great! Wanna send a PR to fix this for next version?

**Comment by kitce** [comment]
I am not familiar with PR, could you help me to do that?

**Comment by simison** [comment]
Sure!

You need to [fork](https://help.github.com/articles/fork-a-repo/) this repository first. Just hit "fork" button on top-right corner of this page:
![image](https://user-images.githubusercontent.com/87168/28291489-54660084-6b53-11e7-9a70-6610f425e61d.png)
Then you you'll have fork of this repo under your username, e.g. at URL https://github.com/kitce/mean

You should then [clone](https://help.github.com/articles/cloning-a-repository/) that repository to your computer.

After that you can do normal meanjs install procedure (mostly just `npm install && npm start`) to get it running.

Now you should [create a new branch](https://github.com/Kunena/Kunena-Forum/wiki/Create-a-new-branch-with-git-and-manage-branches), do your changes, check that everything works for you locally. You can run tests by doing `npm test`.

After all changes are done, [commit and push](https://help.github.com/articles/adding-a-file-to-a-repository-using-the-command-line/) changes to your fork.

Now you can create a pull request (aka PR) following [these instructions](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).

At meanjs we have some guidelines [how to format your commit messages](https://github.com/meanjs/mean/blob/master/CONTRIBUTING.md#commit-message-guidelines) but you shouldn't stress about those too much. We'll modify them if something is funny.

It's really easy and totally worth learning! :-)

This is perfect change because required change seems so small. Your second PR can be a bit more complicated then already. ;-)

**Comment by simison** [comment]
@kitce actually if the change is required only in one file, you can just modify it in github and send pull request directly inside Github. It's suuper easy. :-)

Browse the file, e.g.:
https://github.com/meanjs/mean/blob/master/gulpfile.js

Hit that pen icon:
![image](https://user-images.githubusercontent.com/87168/28308216-360b5bf6-6bae-11e7-9c0c-53468fdc5dc1.png)

**Comment by kitce** [comment]
Thanks for the guide, appreciate that.
