### ISSUE TITLE
Add login page before access to index

### ISSUE THREAD

**Issue by Abdou00** [meanjs/mean#1824]
Hi,
I would like to add a login page before displaying the index, but I have a problem to view the login form. Here is the way I used to achieve it:
```javascript
exports.renderIndex = function (req, res) {
 if (req.isAuthenticated ()) {
  console.log ('The user is logged in');
  res.render ('modules / core / server / views / index', {
   user: req.user
  });
 } else {
  console.log ('The user is not logged in');
  res.render ( 'modules / users / customer / views / authentication / authentication');
 }
};
```

And this is the error returned in the console:
```shell
Error: Failed to lookup "modules/users/client/views/authentication/authentication" in views directory "./"
```

**Comment by mleanos** [comment]
Is `res.render ( 'modules / users / customer / views / authentication / authentication');` a server view or client-side view/route?

You could send the user to the client-side route for login using `res.render('/authentication/signin');`

**Comment by Abdou00** [comment]
Thank you for your help, it works I get to the right url (_http: //localhost/authentication/signin_) but it does not show my login page, my browser referrals: **localhost has redirected you to too many times**. I do not understand why??

**Comment by mleanos** [comment]
Actually, that makes sense.. because *I think* in the case of the user not being logged in, it will redirect them to the login view, but at the same time try to hit the index route (`/`), thus redirecting over & over.

Also, the reason why you don't see your login view, is because there hasn't been a view rendered server side to place your client-side template in. I apologize for my misguided answer. I hadn't thought about the templating/redirecting issue.

If you don't need a server-side template for your "login" page, then you can just do this client-side. By updating [this core client-side route](https://github.com/meanjs/mean/blob/master/modules/core/client/config/core.client.routes.js#L30) by adding

```javascript
data: {
  roles: ['user', 'admin']
}
```

Exactly how this works, https://github.com/meanjs/mean/blob/master/modules/chat/client/config/chat.client.routes.js#L17.

If you indeed need to handle this server-side, it will be a bit more complex. You'll need to create a server-side template for your custom login markup.

If this doesn't help you much, could you please describe in more detail of what you're trying to accomplish?

**Comment by Abdou00** [comment]
Hi, thanks for the reply although I had the solution I forgot to close the sorry issue. I add the roles user & admin and it works. Thank you, thank you very much ;)
