### ISSUE TITLE
Separate backend and frontend

### ISSUE THREAD

**Issue by simison** [meanjs/mean#1849]
As per moving towards [1.0](#1666), one of the first steps is to separate backend from frontend.

Feel free to elaborate in comments what should be done and I'll try add them as a todo list here.

**Comment by lirantal** [comment]
Just to be clear, I think we will take this on in Riess.js as its part of the goal for it

**Comment by simison** [comment]
It's actually a bit unclear to me how the "transformation" from current meanjs to Riess.js would happen, have you elaborated it somewhere already? Might be #1666 is better place for that.

**Comment by lirantal** [comment]
are you referring to the technical process of how we would transform from one to the other?
I think I already discussed what was my point with Riess.js and it's definitely not to start yet another framework, we have enough of those: https://github.com/meanjs/mean/issues/1666#issuecomment-272301457

**Comment by atomixnmc** [comment]
Greate to know there is new progress in this feature in Riess.js . We using Mean.js architecture in a lot of projects and have to split and enhance it by various different ways. We still using it because it's a good start base, that's all we need! After all, developers will want to add more "thing" to it, the framework should just let them "plug and play" easily. A big thumb up for Riess.js @lirantal

**Comment by lirantal** [comment]
thanks @atomixnmc 
you're welcome to chime in on Riess, I opened some issues so it's easier to see the scope of work to get done.
