### ISSUE TITLE
Angular upgrade

### ISSUE THREAD

**Issue by Ghalleb** [meanjs/mean#1850]
Is there a chance that Angular could be updated to v2+?

This project is cool, I used it for some projects. But for new ones it seems a little bit outdated.

I know there is riess.js on track but I think mean.js should not be left with outdated librarie like angular, angular-bootstrap, passport.js, etc.

**Comment by simison** [comment]
Yep! Totally.

Here; #1666 — all coding help would be much appreciated!

I'll close this if you don't mind.

**Comment by Ghalleb** [comment]
Hi @simison 
So mean.js will be updated before 1.0 or we will have to wait until 1.0 (riess.js) is out?
I'm waiting for Angular 2+ so I can try to integrate Nativescript with shared code...

**Comment by lirantal** [comment]
MEAN.js will soon be released with 0.6.0 from current master branch, which as you know doesn't include an angular-cli update.

Hopefully we can start pushing some code into Riess.js which attempts to be the place where we want to start with separating backend and frontend in order to provide this freedom of choosing angular, vue, or react for your frontend needs.

**Comment by Ghalleb** [comment]
Thanks for the response.
So Riess.js will have Angular 2+ but Mean.js will never be updated :-(

Perhaps you can provide an estimate when Riess.js would be "usable", like in alpha? Should I wait Riess.js for my new projects or it will take too much time?

And thanks again for the great job!

**Comment by lirantal** [comment]
Oh no, that's not what I said.
Sorry for the confusion but we're definitely still trying to figure out how to progress.

Just to be clear - of course we will update MEAN.js. As for Riess.js we have opened issues just the past week to discuss a lot of architecture changes so it's not yet ready to use now but we will keep the community updated, no worries. (make sure you subscribe to #1666 thread)

**Comment by Ghalleb** [comment]
OK cool, so I can start a new project with 0.6.0 and update it later when Angular 2+ will be added. 
If I find some time, I will try to do it myself...

**Comment by nlaycock** [comment]
@Ghalleb Did you manage to get anywhere with the Angular2 upgrade?
I have been happily working with with a 0.6.0 project, and now I am thinking its time to start upgrading. I was just wondering if you had any examples of how to bootstrap the application properly.

Thanks mate

**Comment by PierreBrisorgueil** [comment]
hello, @nlaycock we are working on this [here](https://github.com/weareopensource) ([board](https://github.com/weareopensource/MEANie/projects/1)), based on Lirantal work ([Riess.js](https://github.com/lirantal/Riess.js)), a project in order to separate node of MeanJs. We have forked this work (stopped) here in a [Node](https://github.com/weareopensource/Node) repo and created another repo [Angular](https://github.com/weareopensource/Angular). 

In [WeAreOpenSource orga](https://github.com/weareopensource) we dream of creating multiple Back : Node Nest Switft ... and Front : Angular React iOS ... all aligns on feats, in order to allow anyone to compose their fullstack starter composed from subRepo (node angular ...) 
 
Hope some people will join us after the end of a first example of fullstack ([Node](https://github.com/weareopensource/Node)/ [Angular](https://github.com/weareopensource/Angular)) actually gathered [here](https://github.com/weareopensource/MEANie). 

After this we will work on Nest and other techno ... and we will create a presentation website to explain the mindset, with a blog & slack & twitter and communication ... 

feel free to PR and add Issues :) everybody is welcome ! 

(if you test it, actually you need to have postgre installed for the Node, we are adding an option on / off, not to impose the installation of postgre if the user use only Mongoose and no ORM, Riess have added an ORM Sequelize)
