### ISSUE TITLE
Disable lint,eslint,csslint for a particular folder/file extension/file.

### ISSUE THREAD

**Issue by AbinashGupta** [meanjs/mean#1891]
Can anyone please help to disable eslint ? I can t disable it using .eslintignore or .gitignore. Can we disable eslint completely for a project if there is any config setting or switch ?

**Comment by vaucouleur** [comment]
@AbinashGupta There is a eslint task invocation that you can simply remove from the gulp run sequence(s):

https://github.com/meanjs/mean/blob/36887dc3a840e78e5364344fa332e2171315f2d3/gulpfile.js#L449

There are probably plenty of other alternatives. For example, removing altogether all lint related activities from the 'default' task run sequence, etc.:

- https://github.com/meanjs/mean/blob/36887dc3a840e78e5364344fa332e2171315f2d3/gulpfile.js#L485

**Comment by vaucouleur** [comment]
@AbinashGupta 

You edited your original question, and you changed the title from "Disable lint,eslint,cslint" to "Disable lint,eslint,csslint for a particular folder/file extension/file". My comment above applies to your original question.

In order to disable eslint for a specific file, you should be able to use eslint-disable as a comment directly the files you want to ignore. For that and other patterns, see https://eslint.org

For the other linters, please check their respective documentation.

**Comment by simison** [comment]
@vaucouleur thanks for taking this!

@AbinashGupta feel free to re-open if you still have questions around this.
