### ISSUE TITLE
Problems deploying on Heroku

### ISSUE THREAD

**Issue by gkatsanos** [meanjs/mean#241]
I'm trying to deploy my fresh MeanJS app (it's almost the same as the example with maybe a couple of dependencies extra), and I'm posting this for others who'are possibly having the same issue. (maybe a Heroku section on the Readme would be cool?)
1. 
```
1003 info isawu@0.0.1 Failed to exec postinstall script
1004 error isawu@0.0.1 postinstall: `bower install --config.interactive=false`
1004 error Exit status 1
1005 error Failed at the isawu@0.0.1 postinstall script.
1005 error This is most likely a problem with the isawu package,
1005 error not with npm itself.
1005 error Tell the author that this fails on your system:
1005 error     bower install --config.interactive=false
1005 error You can get their info via:
1005 error     npm owner ls isawu
```
After looking around, I had to remove `-    "postinstall": "bower install --config.interactive=false"` in this was **fixed**. (but I'm wondering if the post install script is necessary for the application to be deployed/work correctly?

2.
Then I visit my url, I get some heroku error and got this from the logs:
```
Nov 01 03:15:51 afternoon-eyrie-5693 app/web.1:   NODE_ENV is not defined! Using default development environment 
Nov 01 03:15:52 afternoon-eyrie-5693 app/web.1:   Could not connect to MongoDB! 
Nov 01 03:15:53 afternoon-eyrie-5693 app/web.1:  /app/node_modules/connect-mongo/lib/connect-mongo.js:178 
Nov 01 03:15:53 afternoon-eyrie-5693 app/web.1:            throw err; 
Nov 01 03:15:53 afternoon-eyrie-5693 app/web.1:  Error: Error connecting to database: failed to connect to [localhost:27017] 
Nov 01 03:15:53 afternoon-eyrie-5693 app/web.1:      at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74) 
Nov 01 03:15:53 afternoon-eyrie-5693 app/web.1:      at emit (events.js:106:17) 
Nov 01 03:15:53 afternoon-eyrie-5693 app/web.1:      at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15) 
Nov 01 03:15:53 afternoon-eyrie-5693 app/web.1:      at emit (events.js:98:17) 
Nov 01 03:15:53 afternoon-eyrie-5693 app/web.1:      at Socket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10) 
Nov 01 03:15:53 afternoon-eyrie-5693 app/web.1:      at Socket.emit (events.js:95:17) 
Nov 01 03:15:53 afternoon-eyrie-5693 app/web.1:      at net.js:440:14 
Nov 01 03:15:53 afternoon-eyrie-5693 app/web.1:                  ^ 
Nov 01 03:15:53 afternoon-eyrie-5693 app/web.1:  error: Script restart attempt #4 
```
I realize I have to set my NODE_ENV variable, so I do 
```
$ heroku config:set NODE_ENV=production
Setting config vars and restarting afternoon-eyrie-5693... done, v8
NODE_ENV: production
```
Then I realized I had to ` $ grunt build ` . In the documentation that step is not mentioned.. I guess it's obvious by checking the gruntfile but well... it's a huge stack with many files.

Now I realize from heroku, the libraries from inside public/lib are not loaded and the page breaks. I read somewhere Heroku doesn't have the same folder structure or whatever.. And that I might need to add the lib folder in my repository for it to work. I don't know if this is necessary (and a good practice)

I suggest some documentation improvements, I'll make a pull request and mention it here.

**Comment by ilanbiala** [comment]
@NeverOddOrEven @amoshaviv why don't we add a page to the website with a deployment guide?

**Comment by NeverOddOrEven** [comment]
As with all things lately, lack-of-time / too much going on outside of MEAN.JS. I am still debating how to tackle the deployment documentation, but the approach I am planning currently is two fold:

When using the generator, spit out a "deployment_steps.md"
Publishing a "deployment" section on the website for those cloning the repository

Right now the generator is my priority.

**Comment by ilanbiala** [comment]
@lirantal thoughts in @NeverOddOrEven's approach?

**Comment by diegosanchez** [comment]
I was striving to deploy a Mean.js application into Heroku. The reason is I don't like/want to upload ```public/dist``` files because those are derived from ```public/modules/**/*.js```.

In order to deploy the app, without uploading ```public/dist``` files, I had to install one specific [BuildPack](https://github.com/mbuchetics/heroku-buildpack-nodejs-grunt.git).

Based on that I found some problems deploying the app which forces me to alter the gruntfile.js generated by ```go mean``` generator.

If this solution makes sense for the project we may consider disscussing it.

I've moved gruntfile.js to [Gruntfile.js](https://github.com/diegosanchez/altorostodolist/blob/master/Gruntfile.js). 

Differencies here https://github.com/diegosanchez/altorostodolist/blob/master/Gruntfile.js#L157

**Comment by ilanbiala** [comment]
@diegosanchez what files are being ignored specifically? What files does `grunt build` create for you and what files are missing/errors do you see?

**Comment by diegosanchez** [comment]
(this is my understanding, if there is something wrong please let me know)

1. *What files are ignored specifically?*
When ```config/config.js``` is required either ```config/env/production.js``` or ```config/env/development.js``` are loaded depending on ```NODE_ENV```.  Whether we comment this line, these files won't be imported. 
Why did I comment those lines? See bellow.

2. *What files does ```grunt build``` create for you?*
```grunt build``` task is intended to create both ```public/dist/application.min.js``` and ```public/dist/application.min.css``` as well as it's thought to be run under ```development``` environment.  That's right. If I run the task provided by you everything works fine.
Problems arise when I want to generate these minified files on production not to upload these files into the repository (because these files are derived from others).
**My expectation**: These files (```public/dist/application.min.js``` and ```public/dist/application.min.css```) have to be generated at deploying time by executing ```grunt build``` task on productive server side (```NODE_ENV``` is *production*).
If this task is run under this environment the minified files will be generated with zero-lenth. As a workarround, I directly required ```config/env/all.js``` instead of ```config/config.js``` files because If I had required it (then ```config/env/production.js```) I would have used as sources of my minified files the minified files itself, which don't exist so far.

3. *what files are missing/errors do you see?*
In fact, there aren't neigher missing files nor errors, just this task isn't thought to work under this environment (*production*).
 
4. Because I tried this solution (running ```grunt build``` on production) I have to:
4.a. Move gruntfile.js -> Gruntfile.js because the buildpack require it. [Docs here](https://github.com/mbuchetics/heroku-buildpack-nodejs-grunt)
4.b. Require ```config/env/all.js``` rather than  ```config/config.js``` for it to avoid including  ```config/env/production.js```

I hope you find it  useful, clear enough; If you don't let me know, I'll try to rephrase it.

**Comment by ilanbiala** [comment]
@diegosanchez I'd rather it properly depend on the environment than requiring all.

**Comment by diegosanchez** [comment]
Here is the thing,

Regardless the environment minified files commonly are created on the
deployment time. It doesn't make sense having to upload minimized files
into the repository for us to deploy our application

On 29 January 2015 at 17:14, Ilan Biala <notifications@github.com> wrote:

> @diegosanchez <https://github.com/diegosanchez> I'd rather it properly
> depend on the environment than requiring all.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/meanjs/mean/issues/241#issuecomment-72095690>.
>



-- 
Saludos
DiegoS

------

Diego Sanchez
[image: http://]about.me/sanchez.diego
<http://about.me/sanchez.diego?promo=email_sig>

**Comment by ilanbiala** [comment]
It seems that Heroku deploys just fine with MEAN.js. As for issues regarding minified files in Git, you can open another issue for that if you still think it's an issue.

**Comment by panospost** [comment]
guys i dont know about you, but heroku apps do not deploy fine
https://epratirio2.herokuapp.com/ my app does not work any advise could be help full

**Comment by mleanos** [comment]
@panospost See this issue for more info on deploying to Heroku:
https://github.com/meanjs/mean/issues/1411

**Comment by mleanos** [comment]
@panospost The easiest solution I've found is to use the following steps..

1. Update the [Procfile](https://github.com/meanjs/mean/blob/master/Procfile) to `node server.js` instead of using `npm start`; the latter uses Gulp which won't be installed on Heroku (unless you've configured your app to do so).
2. Remove *public/dist* from your [.gitignore](https://github.com/meanjs/mean/blob/master/.gitignore#L22) so it gets deployed to your Heroku instance.
3. Run `gulp build` locally before you deploy to Heroku. This will minify your css & js files.

On Heroku you will need a few settings set in your Config Vars in your application's settings section:

NODE_ENV = production
NPM_CONFIG_PRODUCTION = true

You may need to add MONGODB_URI as well, if you're using a remote MongoDB instance.

I've added a branch to my fork that demonstrates the changes needed to a MEANJS application: https://github.com/mleanos/mean/tree/heroku-deployment

This method might not work for all use cases. In the case that you feel you need to have the Gulp tasks available to your deployed application, then you will have to move the Gulp libraries (and any other's that are necessary) from your `devDependencies` to `dependencies` in your *package.json*.

**Comment by panospost** [comment]
thanks even though i use  grunt, i ill try it tommorrow :)

2016-11-20 23:52 GMT+01:00 Michael Leanos <notifications@github.com>:

**Comment by panospost** [comment]
i have been troubleshooting my issue it is like i dont have a public/dist
folder and i have to find cdn for every library

2016-11-21 0:10 GMT+01:00 Panos tost <panospost1@gmail.com>:

**Comment by panospost** [comment]
So if i pull the code from your repository the code will work just fine? :)

2016-11-21 0:14 GMT+01:00 Panos tost <panospost1@gmail.com>:

**Comment by mleanos** [comment]
@panospost Theoretically, yes. However, I just pushed that branch up for reference. You can see the two latest commits, to see what changes you would need to make to a project cloned from the latest *master* branch of MEANJS. You still would need to update your Heroku application settings though.

**Comment by panospost** [comment]
yeah no worries i would try to do with your directions and change my
project stuff first

2016-11-21 8:16 GMT+01:00 Michael Leanos <notifications@github.com>:

**Comment by panospost** [comment]
and also i use a remote mongoDb instance and it works withoug putting the
mongodb uri as a variable, the only problem is the angular libraries..

2016-11-21 8:20 GMT+01:00 Panos tost <panospost1@gmail.com>:

**Comment by panospost** [comment]
Hey michael i would really appreciate if you could take a look at my
repository
https://github.com/panospost/newtry2
here is the app as well, i did all your steps but it still cannot solve the
public/dist issue libraries
Appreciate your advice

2016-11-21 8:22 GMT+01:00 Panos tost <panospost1@gmail.com>:

**Comment by panospost** [comment]
scrath that i thing i forgot to upload my application min and min css -.-

2016-11-21 9:37 GMT+01:00 Panos tost <panospost1@gmail.com>:

**Comment by panospost** [comment]
michael i found a work around for my angular libraries but now i dont get
any errors but my front end does not work still
look at my heroku application
https://trytryepratiriopanospost.herokuapp.com/

2016-11-21 11:04 GMT+01:00 Panos tost <panospost1@gmail.com>:

**Comment by mleanos** [comment]
@panospost Do you see any errors? Either console, or server related?

Did you do use the build task locally, before pushing your local app to Heroku?

**Comment by panospost** [comment]
i found a peculiar work around, but now for some reason even though it is
on bower.json and stuff , it does not recognize the angular-simple-logger
package..i think the best thing to do is upload the libraires and etc from
my pc to github, because heroku does not create the public/lib folder so i
changed the express folder tfor the bower_components folder, but i
encounter the error i told you

2016-11-22 0:07 GMT+01:00 Michael Leanos <notifications@github.com>:

**Comment by mleanos** [comment]
@panospost Did you include the angular-simple-logger library in */config/assets/production.js*?

IIRC, the bower libraries will get installed during the Heroku deployment build. This sounds most likely an issue with the additional libraries your application is using, not getting added to the production assets configurations.

**Comment by panospost** [comment]
Listen to me when the deploymrn runs ,heroku does not create the public/lib
directory so i try to call the from the bower_componentd folder but it
gives me the mime type error, i changed the express file but still the
same, it is a dead end either way -.-

Στις 22 Νοε 2016 20:46, ο χρήστης "Michael Leanos" <notifications@github.com>
έγραψε:

**Comment by panospost** [comment]
i changed my express.static(path.resolve(./)); even now that the whole
structure is exposed it still doest recognise the bower_components, any
ideas ?

2016-11-22 22:08 GMT+01:00 Panos tost <panospost1@gmail.com>:

**Comment by mleanos** [comment]
Why isn't Heroku building your *public/lib* folder? Bower should install the libraries in the projects postinstall script. What does your package.json look like, and what are the settings on your Heroku app?

When I deploy my app to Heroku, the bower libraries are installed. Is there any other reason, other than this not working for you, that you have changed to use the "bower_components" folder for your app?

Perhaps it would be better to take this conversation to the [MEANJS Gitter room](https://gitter.im/meanjs/mean)

**Comment by panospost** [comment]
check my github https://github.com/panospost/trytry
my package json the "scripts" section i have copied from your github

2016-11-23 21:08 GMT+01:00 Michael Leanos <notifications@github.com>:

**Comment by panospost** [comment]
hey i dont know if you remember my problem it turns out that my front end
libraries are not downloaded and even when they do , they are blocked
because on mime type in linux environments..in the end i used cdns to solve
this issue

2016-11-23 21:56 GMT+01:00 Panos tost <panospost1@gmail.com>:
