### ISSUE TITLE
LoopBack

### ISSUE THREAD

**Issue by amirmog** [meanjs/mean#351]
Happy new year all,

With the increasing number of interest in loopback and also noticing that Express itself is pushing for loopback (notice the loopback recommendation on the express.com homepage), I wonder if there are any plans for Meanjs to use loopback in the near future?

**Comment by frederik** [comment]
happy new year!

Express and Loopback are both maintained by Strongloop - so that's probably why. I've been running a Mean.JS app with Loopback and Keystonejs in production for 6-7 months now - loopback really makes platforms easier. For smaller projects I've left it out though since it introduces another layer of complexity. 

IMHO we could move meanjs to a point where its data model and connection configuration could be leveraged by loopback more easily (I had to do quite a lot of changes there) so it can be added more easily if you need your mean.js app to expose a public API.

**Comment by quocvu** [comment]
I miss the Swagger integration in Loopback

**Comment by NeverOddOrEven** [comment]
I am interested in anything that claims to make something easier, but this would probably need to be a community driven initiative. We try to keep MEAN.JS fairly agnostic aside from the core MEAN stack components. 

A proof of concept would be helpful, or alternatively considering an implementation in the 0.4.x generator: https://github.com/meanjs/generator-meanjs/tree/0.4-dev

**Comment by quocvu** [comment]
I'd like to clarify, I am not supporting the use of Loopback. I just want Swagger for MEAN.JS. Just created a feature request for <https://github.com/meanjs/mean/issues/352>

I started w/ Loopback and Sails, but quickly were looking for something else and landed on MEAN.JS.
Both frameworks are great in many aspects, but what bothered me was they have a unified storage abstraction layer. While it provides the flexibility and choices of storage, mixing the SQL and non-SQL, gives to users the lowest denominator and I think it was not the best experience whether we work w/ SQL or non-SQL DB. I rather have something that let maximize the use of MongoDB (such as Mongoose) or SQL.

**Comment by ilanbiala** [comment]
LoopBack is somewhat different in its implementation and will cause issues when other people want to just use Express. It probably makes more sense in the generator if anything.
