### ISSUE TITLE
Suggestion: Implement RequireJS via AngularAMD library

### ISSUE THREAD

**Issue by skyserpent** [meanjs/mean#379]
I think it would be a great idea to implement AngularAMD as that would allow for better extensiblity and loading.

https://github.com/marcoslin/angularAMD

**Comment by ilanbiala** [comment]
As far as module loaders go, I think AMD is one of the most complicated, and with tools such as Browserify, we could do much better. I'm open to it, but it's adding a lot of weight for a starter project for people just learning about Node.

**Comment by skyserpent** [comment]
It would add greater flexibility to MEAN. As code gets more advanced, AMD or Browserify would be very helpful for dependency management and lazy loading. Browserify would be a bit easier for newcomers to use and it does serve some advantages over RequireJS.

**Comment by ilanbiala** [comment]
Yes, but most people are either starting out with MEAN because of its simplicity or because it's simple and barebones and easy to add on to. Adding a module would work against this in my opinion.

**Comment by skyserpent** [comment]
You're right yet it would still add to the overall 'framework' side of things. Not to say that MEAN isn't good without it because anyone can add it if need be. :grinning:

**Comment by ilanbiala** [comment]
@skyserpent if @NeverOddOrEven thinks it could be useful in the Generator, then we should do it there and let people choose if they want it.

**Comment by darko-mijic** [comment]
@ilanbiala, in my opinion complexity that Browserify will introduce is a price I am willing to pay. :)
I also agree that AMD is not a good idea. 

I think that isomorphic JavaScript and the ability to share modules between frontend and backend goes very well with the idea of full-stack JS framework. And it definitely goes well with DRY principle. 

I am currently working on a port of MeanJS to support Browserify. My end goal is to have better solution for validation. But I will be satisfied if I only end up with support for modules used on server side in the client side code (like lodash etc.) I am trying to decide how much of validation can be reused between client and server so there is almost no duplication. I am also looking into Mongoose browser component.

Here are some resources and things I am looking into:

**ng-autobootstrap** project simplifies bootstrapping Angular components:
https://github.com/maximilianschmitt/ng-autobootstrap

**ng-autobootstrap** Gulp plugin (there is no solution for Grunt):
https://github.com/maximilianschmitt/gulp-ng-autobootstrap

**ultimate-seed** - this MEAN stack boilerplate uses Browserify:
https://github.com/pilwon/ultimate-seed

**Mongoose browser component**
http://mongoosejs.com/docs/unstable/docs/browser.html
http://thecodebarbarian.com/2015/02/20/better-angularjs-form-validation-with-mongoose

If discussion continues maybe it is good idea to rename this issue or to create new one because Browserify should be in the title.

**Comment by ilanbiala** [comment]
If you would like to submit a PR to have it in the generator, we can work with that.
