### ISSUE TITLE
Cordova app with angularjs

### ISSUE THREAD

**Issue by NavneetNile** [meanjs/mean#468]
I am trying to make android mobile app using cordova. I have created an application in MEAN.js framework and it is working properly and now i am trying to convert this application into an android mobile application so i tried a lot but could not find a proper solution. Please help me to find the way for creating android mobile app using cordova. Thankyou.

**Comment by dotch** [comment]
take a look at [ionic](http://ionicframework.com/), which is based on angular and takes care of the native wrapping with cordova for you. however, it does not allow you will have to do a lot of manual work to extract your angular client side logic from your meanjs application first.
Otherwise look at the [cordova docs](http://cordova.apache.org/docs/en/4.0.0/), google some tutorials and ask on stackoverflow when you have specific questions.

**Comment by ilanbiala** [comment]
@dotch is correct. Please direct these questions to a more appropriate forum such as stackoverflow.

**Comment by karan-kapoor90** [comment]
@wesleyfsmith and @britztopher I believe you've done something like this. Could you please point me in the right direction? Haven't got anything on it from the ionic team or SO yet. Any resources that you could care to share please?
