### ISSUE TITLE
Why do we have all.js if we have development.js

### ISSUE THREAD

**Issue by wesleyfsmith** [meanjs/mean#472]
So currently, if I specify a 3rd party library to be included under all.js, it only gets included when NODE_ENV is set to 'development'. This confused me for a while when I was starting with mean.js and it was a bitch of a 'gotcha' before I realized I needed to include the minified files under production.js

What I'm getting at is, why do we even have an all.js file if it only getting loaded during development mode? Should we just move everything development.js? Wouldn't that be clearer?

**Comment by lirantal** [comment]
this is on 0.4 or master? sounds like a bug

**Comment by wesleyfsmith** [comment]
This is on master. I've been doing it for a while, I only realized that it didn't seem like intended behavior.

**Comment by mbukosky** [comment]
I ran into this "issue" before. I never really understood the purpose of the all.js.

**Comment by lirantal** [comment]
looking at the code in config/config.js it shows as follows:
```javascript
/**
 * Load app configurations
 */
module.exports = _.extend(
	require('./env/all'),
	require('./env/' + process.env.NODE_ENV) || {}
);
```
which means that it will extends all.js with any configuration of NODE_ENV.
can you explain what exactly do you mean include a 3rd party?

**Comment by emosher** [comment]
I encountered this problem recently and thought I would add what I learned in the hopes that this might help others.

As the [MEAN.JS docs say](http://meanjs.org/docs.html#configuration), `config/env/all.js` contains defaults that will be overwritten by the corresponding environment configuration (secure, prod, etc).  In my head, I thought that meant that you would only need to list a file once in the config.  So for example, if you had `path/to/angular.js` in the array `assets.lib.js`, you need to list that in the environment configurations.  In other words, the *entire* array is overwritten when the call to lodash's extend happens.  

While a way to preserve array values may be a nice-to-have in the future, that's not the case right now.    You just need to be sure to understand how things are working in order to use Mean.js effectively.  Hopefully that helps.

**Comment by simison** [comment]
See discussion from https://github.com/meanjs/mean/pull/557

**Comment by lirantal** [comment]
Closing issue.
