### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by codydaig** [meanjs/mean#517]
I've heard talk about incorporating an admin panel into MEAN.js, but haven't seen much done towards it. This is the only reason I haven't switched to the MEAN stack. I'd love to help out on this project. 

Has anybody started this process, or at least come up with how they want it done?

**Comment by ilanbiala** [comment]
@codydaig As of now we're focusing on pushing 0.4.0, and you can see what our plans our by checking that milestone. Please search for open issues before just opening one by the way, because #41 is already open for discussion. If enough people still need an admin page, then we can look into that for 0.4.x or 0.5.0.
