### ISSUE TITLE
Deploy on Amazon Web Services

### ISSUE THREAD

**Issue by mafcm** [meanjs/mean#524]
Hi,

Please I would like to deploy an application build by MEAN.JS on Amazon Web Services but I don't know how to start.

Please, could someone help me ?

**Comment by andreafdaf** [comment]
when I was almost finished I realized that maybe you use windows... anyway the first steps are common to any OS you choose:

- launch an EC2 instance (the size depends on your needs, but since you're starting use the free tier)

- assign a keypair to connect to your instance, save this key in a secure location!

- configure the security group used by the instance to open ports 22 (ssh) 80 (http) 443 (ssl)

- assign a static IP to your instance (Elastic IPs)

- go to Route53 and configure your domain, then create an A record set and point it to the IP assigned above

- deploy your code to a git repo

- ssh to your instance:
```
ssh -i yourkey.pem ubuntu@12.12.12.12 //user is ubuntu by default, 12.... is the IP you assigned to your instance
```

- *this nginx part might be skipped and you can use your node app "directly" but nginx is a good choice for serving static files, handling ssl, etc (that's not shown here)... and is always something worth knowing!*

- install nginx:
```
sudo apt-get update
sudo apt-get install nginx
```

- configure nginx (/etc/nginx/sites-available) to create a new server that proxies to your MEAN app, the following is a super basic config:
```
server {
    listen 80 default_server;
    server_name app.domain.com;
    location / {
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_pass http://127.0.0.1:PORT;
    }
}
```

- make this site available:
```
sudo ln -s /etc/nginx/sites-available/yourapp /etc/nginx/sites-enabled/yourapp
```

- remove the default and restart nginx:
```
sudo rm /etc/nginx/sites-enabled/default
sudo service nginx restart
```

- install git, nodejs, mongodb (unless you're using mongolab or similar DBaaS) and all npm global packages needed (as you would do on your local machine)

- clone your git repo somewhere

- cd your project, then:
```
npm install
grunt build
NODE_ENV=production [ANY_ENV_VAR_YOU_NEED=...] grunt
```

voilà! there could be some minor issues during this procedure, other steps might be needed based on your app, anyway that's more or less all you need for a basic setup (or at least now you know the steps)

let me know :)

**Comment by lirantal** [comment]
Closing issue
