### ISSUE TITLE
before and after on user module unit tests

### ISSUE THREAD

**Issue by gilesbradshaw** [meanjs/mean#525]
Wouldn't you be better with beforeEach and afterEach?

**Comment by ilanbiala** [comment]
Which parts/files specifically?

**Comment by codydaig** [comment]
I'm assuming @gilesbradshaw is taking about changing before and after ti beforeEach and afterEach. So instead of creating a two users as the beginning for all tests to share, it would create new users for each test to share. Then after each test it would reset the database before moving onto the next test.

https://github.com/meanjs/mean/blob/0.4.0/modules/users/tests/server/user.server.model.tests.js

If this is something we want, we could discuss it with #684 otherwise, I think we should close this issue.

**Comment by lirantal** [comment]
I don't think it's an all or nothing. Some tests require other tests to run before them and are based on the previous test.

I do however suggest @gilesbradshaw that if you want to add more tests (and there are many places to add them, whether it's the backend, frontend, or e2e) then just go ahead and create a PR.
