### ISSUE TITLE
how to remove #!  from url

### ISSUE THREAD

**Issue by nuwan98** [meanjs/mean#592]
http://localhost:3000/#!/home

i want to get  
http://localhost:3000/home
as my home url
can somebody  please help....

**Comment by pgrodrigues** [comment]
That happens because 0.3.0 is using angular with hashbang mode enabled and consequently html5mode disabled.

If you want to change just add  `$locationProvider.html5Mode(true);`. But be warned that the routing will most likely break since expressjs in mean 0.3.0 is configured in a way to support the fact that angular is running with hashbang mode enabled, and all links in html files have the hasbang.

On the other hand, mean 0.4.0 is using html5mode (hashbang mode disabled) in case you might want to take a look.

**Comment by andreafdaf** [comment]
it's pretty simple to make it work on 0.3:
- change all endpoints to /api/what-it-was-before
- if someone requests /some-route (with no api in front) simply redirect them to /#!/some-route and angular will take care of removing the #! (if you followed pgrodrigues steps) and everything is back to normal

wastes a quick roundtrip but works ok, maybe there is a better way

**Comment by nuwan98** [comment]
thank you friends, it is very helpfull

**Comment by babagimanoj** [comment]
thanks pgrodrigues , that saves my time.

**Comment by codydaig** [comment]
@nuwan98 Did your question get resolved?

**Comment by lirantal** [comment]
let's close, otherwise @nuwan98 you're welcome to re-open if this issue is still happening on the 0.4.0 branch.
