### ISSUE TITLE
yo generated controllers / services / etc. do not load

### ISSUE THREAD

**Issue by mhale650** [meanjs/mean#605]
Hi,

I am trying to refactor my code into different files but running into an issue.  Right now I have multiple controllers in my articles/controllers/articles.client.controller.js file.  I generate an additional controller using yo, it seems to work fine, I copy the controller into that file (here following a youtube video so pretty sure I got that right), but then the controller can't be found.

I'm having the same issue with services, routing, etc., is there something I'm forgetting to do? I'm pretty new to all this so it could be something painfully obvious.

Thanks!

**Comment by mleanos** [comment]
What does do the controller declarations look like in your articles.client.controller.js?

My guess is that you're not declaring it correctly in the new files, due to (perhaps) a reference to the module being a variable in your original file.

More details would be helpful... if just a mere code snippet. Either way, it's most likely with your controller declaration.

**Comment by mhale650** [comment]
The controller in the articles.client.controller.js are declared as follows:

```javascript
var articleApp = angular.module('articles');

articleApp.controller('ArticleController1', [
//...etc.
]}

articleApp.controller('ArticleController2', [
//...etc.
]};
```

Thanks for any help

**Comment by mhale650** [comment]
Turned out I needed to give it time to compile after adding a file...

Marking it as closed.  Dumb mistake!
