### ISSUE TITLE
Routing - Route error handling only at Angular (client-side)

### ISSUE THREAD

**Issue by C-YanHua** [meanjs/mean#677]
Hi meanjs developers,

I have been following 0.4.0 for quite awhile and I notice the latest commit includes route error handling at both server and client side as oppose to the previous version whereby route error handling is solely done on the server side and any invalid route at client side is simply redirected to the home page.

I was wondering would it be possible to solely rely on Angular to perform route error handling?
Would it be possible to simply perform a res.status(404).send(...) in the "renderNotFound" function which in the case would require Angular to catch all 404 errors and redirect them to a 404 error page at the client side.

What would be the reason for performing route error handling at both server and client side? Is the current committed approach more viable? Sorry for asking, but i am rather new to web development...

Appreciate your replies. thanks!

**Comment by simison** [comment]
Hey, thanks! I wrote that solution.

Server side handling makes sense for /api/* paths which are supposed to return json answer (or html if client requests so) and for /public/* paths so that browsers can catch missing asset files with appropriate error at console. Any other wrong routes are passed for Angular (i.e. server just pushes index.html and Angular ui-router then checks if the route exists or not). 

In case of Angular headers are already sent to the browser, so it can't produce proper 404 header error code, which is a bummer. Getting 404 at least for some of the routes is a good thing and very important if one is to build REST api clients outside main Mean app.

The problem with non-public/api route errors is that the server doesn't know about them since routes are defined only at frontend. It would need quite a hack to make it isomorphic from its current state, so it would need to be well thought to avoid duplicate route definitions. (Could a Gulp task handle it somehow?)

Does this answer to your question or did I miss something?

**Comment by C-YanHua** [comment]
Hi simison, thanks for the explanation!

But i am facing a slight issue with this approach.
In my application, I am trying to utilize express parameters to search for a user profile by his/her username.

So in the server side "users.server.routes.js", i have the following route:

```  
app.route('/api/:username').get(users.read);

app.param('username', users.userByUsername);
```

and in client side "users.client.routes.js", i have the following state:

```
state('profile', {
  url: '/:username',
  templateUrl: '/modules/users/views/profile/profile.client.view.html'
}).
```

and a service to handle the request:

```
angular.module('users').factory('UserProfile', ['$resource',
  function($resource) {
    return $resource('api/:username', {username: '@username'}, {});
  }
]);
```

As you can see, if a user were to enter "localhost:3000/rubbish", whereby considering the username "rubbish" does not exist, it will be considered a valid route unless the function "users.userByUsername" performs a response of http 404 error, back to the client side.

I tried to perform a redirect to "/not-found" of the server side, but angular will simply render the "profile.client.view.html" after rendering the 404 page.

So my concern is, how should i go about handling this route error?
It is, in a sense, a valid route, but invalid as the username does not exist...

Thanks for your help!

**Comment by simison** [comment]
Maan, leaving prefixes (e.g. ./profile/) out of routes you're entering a famous router resolver hell. :-) I really like how Medium.com solved this with their "medium.com/@username" urls (that @).

In this case I'd try to build something with route resolvers, which is anyway a way to go and future Meanjs versions are moving to that direction as well. Check this: https://github.com/johnpapa/angular-styleguide#route-resolve-promises and https://github.com/meanjs/mean/pull/636 for work-in-progress.

So that promise would resolve with failure. I'd return 404 from the API for not-found users — see, the route at server side can be valid, but you can still return 404 from controller when user/article/etc doesn't exist.

In case of promise failure at route resolver, you can either redirect to /not-found or show some not-found message at profile view. You can even redirect at profile-view-controller, but that's a bit dirty practise.

**Comment by C-YanHua** [comment]
Hi simison, thanks for the information! 
Didn't know what i was getting myself into, haha! I just wanted to mimic what github was doing for viewing of user profile.

Thanks for the advice! Will look into applying route resolvers in my application.

**Comment by lirantal** [comment]
@C-YanHua if you got all the help you need from @simison I guess we can close this issue?

**Comment by C-YanHua** [comment]
Hi, for those who might be interested in my approach on performing route error handling at Angular only. The following is my solution to my problem (It is neither exactly perfect, nor elegant):

So at the server side, i modified/added the following:

In "core.server.routes.js":
```
// Define HTTP error pages.
app.route('/500-server-error').get(core.sendServerError);
app.route('/404-page-not-found').get(core.sendPageNotFound);

// Return page not found error for all undefined api, module or lib routes.
app.route('/:url(api|modules|lib)/*').get(core.sendPageNotFound);
```

In "core.server.controller.js":
```
exports.sendServerError = function(req, res) {
  res.status(500).send();
};

exports.sendPageNotFound = function(req, res) {
  return res.status(404).send();
};
```

In users.authorization.server.controller.js:
```
exports.userByUsername = function(req, res, next, username) {
  User.findOne({username: username}).exec(function(err, user) {
    if (err || !user) {
      return res.redirect('/404-page-not-found');
    }

    req.profile = user;
    next();
  });
};
```

In users.client.config.js (personally I feel that this should move into core config):
```
case 404:
  // Transit to 404 not found page.
  $injector.get('$state').transitionTo('404-page-not-found');
  break;
case 500:
  // Transit to 500 internal server error page.
  $injector.get('$state').transitionTo('500-server-error');
break;
```

In core.client.routes.js:
```
state('404-page-not-found', {
  templateUrl: '/modules/core/views/404.client.view.html'
}).
state('500-server-error', {
  templateUrl: '/modules/core/views/500.client.view.html'
});
```

Add the necessary view pages.
Thanks @simison for all the advice and help provided. I chose to ride on the http interceptor that was utilize by mean to catch 404 errors, but it is still advisable to perform route resolver for the routing.
