### ISSUE TITLE
Route / request prefix support

### ISSUE THREAD

**Issue by debrouxl** [meanjs/mean#715]
I need to make a MEANJS-based application accessible through an existing reverse proxy which acts as a front-end for multiple other applications. In such a case, all client requests, and all server routes, need to be prefixed.
Adding route prefix support requires a number of improvements and fixes, and for some of those, I'm not sure which the best course of action is. I think that the route prefix feature belongs upstream anyway (because others might need it as well), hence this issue, for discussion and decision purposes at first :)

For now, on the server side, I have implemented a half-measure which works: the reverse proxy strips the prefix, which sidesteps changing every server route to take the prefix into account. Of course, server routes need prefix handling, but littering every server route file with a require of the config, and every route definition with explicit prefix handling, looks insane to me.
A better way, IMO, is to use a thin wrapper for the express app object, whose sole goal is to add the user-specified prefix in front of every route definition before delegating to the actual express app object. And there may be other, more idiomatic methods I haven't thought about.

In order to save a bit of time, here's a sketch of the changes for the client side (sorry, no proper diff right now - the local application is currently based on a 3-month-old version of the 0.4.0 branch, I need to update...):
* in config/env/*.js, a user-specifiable prefix accessible at config.app.prefix;
* in config/lib/express.js, initLocalVariables(), injecting config.app.prefix or '' into app.locals.prefix:
```
	app.locals.facebookAppId = config.facebook.clientID;
 	app.locals.jsFiles = config.files.client.js;
 	app.locals.cssFiles = config.files.client.css;
+	if (config.app.prefix && config.app.prefix !== '') {
+		app.locals.prefix = config.app.prefix + '/';
+	}
+	else {
+		app.locals.prefix = '';
+	}
```
* in config/lib/express.js, initErrorRoutes(), redirecting to either /server-error, or <prefix>/server-error, depending on config.app.prefix (upstream changed this hunk in the meantime);
* in modules/core/server/views/layout.server.view.html, leveraging the <base> tag in the HTML
```
-	<base href="/">
+	<base href="/{{prefix}}">
```
* in multiple files which can be found by grepping, removing the leading '/' from the routes and attributes of <img> tags. For instance, not limited to:
```
modules/users/client/controllers/*.js
modules/users/client/controllers/settings/*.js
modules/users/client/views/settings/manage-social-accounts.client.view.html
modules/users/tests/client/authentication.client.controller.tests.js
```

**Comment by mleanos** [comment]
@debrouxl I thought I had a similar need. However, turns out mine isn't a need at all :) My little thought experiment reminded me of this issue you opened. When I first read it, I didn't have much perspective. I think you have something here. However, I'd like to understand your need a bit more.

Could you elaborate on the relationship between your proxy & the client applications? I'm a little fuzzy on that aspect of it. If you could provide some practical examples, that may help. 

How would your front-end application react to these *prefix* routes? Would they just propagate it down to the back-end to determine what `/api` to hit? Would you send them to a separate front-end application depending on the *prefix*?

For the back-end handling of the *prefix*, I think a express middle-ware would suffice. Have you explored that?

**Comment by debrouxl** [comment]
The reverse proxy multiplexes access to completely separate applications (different physical servers, different implementation languages, different programmer teams) in the following way:
```
https://<domain>/app1/<application 1 static files + routes>
https://<domain>/app2/<application 2 static files + routes>
```
etc.

Clients, usually Web browsers, need to make requests below
```
https://<domain>/app1/
https://<domain>/app2/
```
for a given application to work. The applications running on the server behind the proxy need to either be able to deal with that "/app1" or "/app2" prefix by themselves, or have any prefix stripped from requests by some rewriting rule before they reach the application (which is what I did for now, it's a one-liner in the nginx config).

Since I created this issue, I found about StrongLoop's restApiRoot: http://docs.strongloop.com/display/public/LB/Versioning+your+API . This only deals with the API, AFAICS.
For meanjs, I'm thinking about a stronger form, which could use separate static route prefix scalar and REST API route prefix both defined into the config, for effortless (from the meanjs framework user's POV, that is ;) ) prefix handling.

I haven't looked into Express middleware, but integration thereof belongs to upstream meanjs :)

**Comment by codydaig** [comment]
@debrouxl This seems to be a unique use case. If I were you, I would look into express middleware and see what options there out there. If you come up with a solution you can submit a PR for discussion to see if it's a direction the community would like to take.

**Comment by codydaig** [comment]
@debrouxl See #313. You may be able to spark discussion in that issue. It seems like there was a solution with nginx just had to change absolute paths to relative.

**Comment by debrouxl** [comment]
Looks like this issue is mostly a duplicate of #313, which I missed when searching in the issues list.
We are both using a reverse proxy, a route prefix, and the client code uses absolute paths which fail to work when there's a route prefix, so we both patch the client code.

As outlined in my first post, the server-side code needs patches as well for server-side routing, _if_ we want to make meanjs able to support non-empty route prefix without using a reverse proxy in front of it (whose goal is to strip the prefix, precisely). StrongLoop applications can already do that.
But I couldn't say which is the best course of action for patching server route definitions in meanjs. I _think_ that a thin wrapper for the Express "app" object, which would transparently inject the user-specified route prefix before delegating route registration to the real Express middleware, should fit the purpose. However, I'm clearly less experienced wrt. Express than the meanjs maintainers and multiple meanjs contributors, so there may be better ways I don't know about - hence an issue for discussion :)

A possible resolution of this issue and #313 could be to fix the client-side code to use relative paths (needs to be done in any case), based on the injected base with prefix, and document how to configure nginx to strip the route prefix. But integrating direct, reverse proxy-less support for a route prefix would be easier for the users of meanjs :)

**Comment by ilanbiala** [comment]
Since this is a specific case, I'd rather not keep this open on GitHub and instead refer you to Gitter or Stack Overflow or another Forum.

**Comment by PierreBrisorgueil** [comment]
I'm not sure it's a specific case. But I see this case otherwise.

In many companies , you do not have an authentication service application, it would be crazy, but it's a global authentication service (play with header in general). So it is possible (and even in many cases) want to use meanjs , client and server , but not the management of authentication, or at least go through an intermediate step :).

For this we use mocks in development. Who are only making a step reverse proxy (probably in node) between the client Meanjs and the server Meanjs, it change header, for api request, and api check if header is ok. It's only an other step who make a simple redirection. 

If everything is on the same server (general case), for doing something like this, you juste have to change port questioned by the client side. In development, with this, your request will do this : 

MeanJs client -> Proxy (Mock) (localhost:ProxyPort/api/*)
(Proxy (Mock) will change header) 
Proxy (Mock) -> MeanJs Server (localhost:ServerPort/api/*)
MeanJs Server -> Proxy (Mock)
Proxy (Mock) -> MeanJs client

I hope I have been understandable :) sorry for english !

So for me it' not a specific case, but something for all company use case. 
:) But I would not say it's necessary to integrate this, but it is necessary to make this easier or not ? :) 

i have a look actually for a personal test :)
