### ISSUE TITLE
1. authorization: client side,  2. authentication and authorization: socket calls

### ISSUE THREAD

**Issue by mg1075** [meanjs/mean#772]
1. There is an angular Authentication service on the client. Is there a reason why the client does not also have an Authorization service? I see the client routes pass data object with an array of roles, but is there an example showing the canonical way to leverage those client side roles?

2. There is a policies folder on the server in a module such as the "articles" module. Then the server routes of the modules incorporate the authorization rules established in the policies file. What about server-related socket calls in the "chat" module? Where is authentication and authorization? Where is acl?

Is there documentation explaining how these parts work together?
Apologies if I'm missing something obvious here.

**Comment by lirantal** [comment]
@trainerbill @rhutchison

**Comment by mleanos** [comment]
@mg1075 I can't really speak too much to your first question, regarding the services. My understanding is the `auth.server.routes` don't necessarily need a client service. These routes will be used from external calls, more often than not. For instance `/api/auth/forgot` will be accessed directly from an email when using the *Password Forgot* feature. That's initial guess.

As for your second question, I can be a bit more certain on my answer; I've used Socket IO quite a bit. The *calls* made to the server from the client, don't require authentication on the server. This is because the Authenticated User is attached to a Socket IO instance on the server. If there has been no authentication, the client won't (and can't) connect to the Socket server. You can see this in the below snippet from `config/lib/socket.io` https://github.com/meanjs/mean/blob/master/config/lib/socket.io.js#L81
```
// Use Passport to populate the user details
        passport.initialize()(socket.request, {}, function () {
          passport.session()(socket.request, {}, function () {
            if (socket.request.user) {
              next(null, true);
            } else {
              next(new Error('User is not authenticated'), false);
            }
          });
        });
```

**Comment by mleanos** [comment]
@mg1075 If you're worried about not having Authorization on the server, for your Socket config listeners, then you can implement any sort of logic to check Authorization, at the listener. For instance, if you would like to make sure someone has *permission* to send a message to a particular user, then you can put that check in your `chat.server.socket.config` listener.

I have a few custom Modules that use Socket IO, and I have additional validation on my server side listeners. I can see a more robust *Socket Auth* solution implemented here, but it might not be necessary due to the nature of sending Socket.emits(). They *usually* don't manipulate any sort of back-end *resources*. 

At least this seems to be the case for how the Socket/Chat features are currently implemented. It appears that the Chat feature was meant to be a simple starting point, for a full fledged Chat module.

**Comment by codydaig** [comment]
@mg1075 Do you still need help or can this issue be closed?

**Comment by bastianwegge** [comment]
Is there any chance to test this on the server-side?

**Comment by mleanos** [comment]
@bastianwegge Are you referring to server-side test coverage? There is a test file for the Chat socket, however there aren't any tests defined in it. 
https://github.com/meanjs/mean/blob/master/modules/chat/tests/server/chat.socket.tests.js

I'm not too familiar with this test framework, so I'm unsure of how to mock the Socket server. It may involve initializing the Socket in the test; similar to how the express server is instantiated here.
https://github.com/meanjs/mean/blob/master/modules/users/tests/server/user.server.routes.tests.js

This may be a good starting point... http://liamkaufman.com/blog/2012/01/28/testing-socketio-with-mocha-should-and-socketio-client/
http://stackoverflow.com/questions/22461877/is-it-possible-to-test-socket-io-app-with-mocha

**Comment by bastianwegge** [comment]
@mleanos thank you for the immediate answer, but it does not help me at all. I investigated into this the complete morning. I wouldn't ask if I didn't. I'm currently trying to implement `passport.socket.io` which seems to be maintained and testable. Maybe someone has a hint that boosts my progress?

**Comment by mleanos** [comment]
@bastianwegge What exactly do you need help with? Test coverage? Or implementation of Socket.io?

**Comment by bastianwegge** [comment]
I want to test the socket.io configuration that's loaded automatically by folder `server/sockets/*`. Since there actually is no implementation of the test right now.

The "problem" is that you cannot pass cookie variables neither to socket.io nor to socket.io-client implementation as of my understanding. We wan't to implement socket.io features using test-driven development like the following:

1. Feature request: Customer want's to list all active and logged in users
2. Write the test: socket.io implementation accepts connect only from logged in users
3. Write the code
4. Write the test: angular implementation of the socket registration
5. Write the angular-code

Right now this does not seam possible. I've implemented a feature only testing the angular-part like in the chat-controller example. But that does not satisfy me.

**Comment by bastianwegge** [comment]
@mleanos maybe you wanna have a chat about that?

**Comment by ilanbiala** [comment]
@bastianwegge @mleanos is there anything happening with this, or can it be closed?

**Comment by bastianwegge** [comment]
@ilanbiala in my oppinion we can close this -> https://github.com/meanjs/mean/pull/865
