### ISSUE TITLE
How is authentication working here?

### ISSUE THREAD

**Issue by sparshy** [meanjs/mean#786]
I am new to MEAN stack, can someone tell how is authentication actually working here?
 When the user logs in,where is the USER json object stored. The code is    
    
    $scope.authentication=Authentication;
    // If successful we assign the response to the global user model
    $scope.authentication.user = response;
 but in console window.user returns null

*Another question, how the app retains the user JSON object when the page is refreshed? After the page is refreshed window.user returns the user JSON object, I don't see this object in the Local Storage or Session Storage, neither do i see any ajax being made to the server to fetch this object. 

Thanks

**Comment by mleanos** [comment]
@sparshy I'm not super familiar with the authentication logic, but perhaps these are what you're looking for... 

https://github.com/meanjs/mean/blob/master/modules/users/server/config/users.server.config.js#L21
https://github.com/meanjs/mean/blob/master/config/lib/express.js#L112
https://github.com/meanjs/mean/blob/master/modules/users/server/config/strategies/local.js#L12

From what I understand, these work together to validate, store, and retrieve the user data. With every response sent back from the server, the `$http` interceptor in `users/server/config` will deserialize the data.

**Comment by sparshy** [comment]
@melons this is the server side implementation, how the server deserializes the userId to get user object. Can you please explain the client side implementation in angularjs, what happens when you first sign in and when the pages is refreshed? Particularly the `Authentication` service.

Also, can you confirm that is the entire user object `id:xyz, displayName:abc .... ` being sent with every response from the server??

**Comment by andreafdaf** [comment]
@sparshy you tagged the wrong person in the above comment :) anyway!

The page loads from the server only once, and the user object is embedded in it when you render the index page (the user or null of you are not logged)... the angular service just wraps the user from the window object, if the user is there is like telling to the app "this user is logged in and that's his data"; otherwise when you login successfully the response contains the user object with your data and now the angular app knows that you are logged in!

What keeps you logged in is your session stored in Mongo, each time you request something from the server it will check your session and know if you're logged, what access privileges you have and hence what resources you can access and how.

Again remember, when you refresh the page is like starting over from the top, the main point in a SPA is that the page never refreshes! Page refresh? Load index -> user is logged so it's embedded, user is not logged so is null -> load all your scripts -> angular bootstraps -> Authentication services wraps window.user -> angular now knows how to behave, window.user = data means logged, window.user = null means not logged

Is fairly easy to trick a SPA to think that you are logged and to make it show a particular view or element that should be hidden... as for angular concern:
- is there a user in the Authentication.user (aka window.user)? ok, so the user is logged
- I called api/signin and received a 200? save the response as the user object, the user is logged
- I've made a call to the server (no matter what where when...) and received a 401? user is not logged, set Authentication.user (aka window.user) to null

The main point is not forbidding a user (or non user) to navigate to a view (that's just a usability issue) but forbidding access to the back-end routes that retrieve or manipulate data that this user (or non user) don't have the right to access or manipulate

As for "can you confirm that is the entire user object id:xyz, displayName:abc .... being sent with every response from the server?" the answer is no, user object is sent:
- when you load index (embedded as window.object)
- when you login successfully
- when you update the user successfully

**Comment by sparshy** [comment]
Hi @andreafdaf thanks for the answer man, yeah its clear to me now except one doubt

See any property attached to window object , will be destroyed on page refresh, right? See in console try doing window.mean={name:"mean"}, once your refresh the page window.mean is no longer available, how is window.user available even after page refresh?

**Comment by andreafdaf** [comment]
@sparshy because when you refresh your page the first thing it ask for is the main HTML and as you can see here (core.server.controller.js):
```
res.render('modules/core/server/views/index', {
  user: req.user || null
});
```
the user is passed to the render function (req.user is put there by an express middleware that runs before the route matcher)

and then the user object is injected (layout.server.view.html)
```
<!--Embedding The User Object-->
<script type="text/javascript">
  var user = {{ user | json | safe }};
</script>
```
so that's why it's still there even after you refresh!

**Comment by sparshy** [comment]
Thanks to you man @andreafdaf , finally I understand it :+1:

**Comment by codydaig** [comment]
@sparshy Is this issue resolved then?

**Comment by sparshy** [comment]
Yeah @codydaig
