### ISSUE TITLE
$injector:modulerr when deploying to Pivotal

### ISSUE THREAD

**Issue by jd-carroll** [meanjs/mean#861]
The following:

```
$ git clone https://github.com/meanjs/mean.git && cd mean
$ npm install
$ grunt build
$ cf login -a api.run.pivotal.io
$ cf create-service mongolab sandbox mean-mongo
$ cf push
```

Produces:
```
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.17/$injector/modulerr?p0=mean&p1=Error%3A%2…epressible-petrology.cfapps.io%2Flib%2Fangular%2Fangular.min.js%3A17%3A381)
```

When I navigate to the link provided by `cf push`

I'm still new to all of this, so am I missing / not changing something that I need to be?

**Comment by codydaig** [comment]
@ryanjbaxter Do you know what could be going on here? Is it CF related?

**Comment by ryanjbaxter** [comment]
Looks like this was caused by the changes in #759 which added `public/lib/angular-messages/angular-messages.js` to the default and production environments but not the CF environment.  Is there any way to inherit what is done in the production environment file in the CF environment file so this doesn't happen again?

**Comment by lirantal** [comment]
@rhutchison can you take a look?
