### ISSUE TITLE
user.server.model.js error Discriminator : Schema.apply Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by Solidary** [meanjs/mean#892]
HI,
I would like to create two classes Student and Teacher whom are going to inherits from User.
So I modified the User and the new class is :
```
'use strict';

/**
 * Module dependencies.
 */
var mongoose = require('mongoose'),
	Schema = mongoose.Schema,
	crypto = require('crypto'),

	util = require('util'),
	_ = require('lodash');

/**
 * A Validation function for local strategy properties
 */
var validateLocalStrategyProperty = function(property) {
	return ((this.provider !== 'local' && !this.updated) || property.length);
};

/**
 * A Validation function for local strategy password
 */
var validateLocalStrategyPassword = function(password) {
	return (this.provider !== 'local' || (password && password.length > 6));
};

/**
 * User Schema
 */
function BaseSchema() {
	Schema.apply(this, arguments);
	util.inspect(this);
	this.add({
		firstName: {
			type: String,
			trim: true,
			default: '',
			validate: [validateLocalStrategyProperty, 'Please fill in your first name']
		},
		lastName: {
			type: String,
			trim: true,
			default: '',
			validate: [validateLocalStrategyProperty, 'Please fill in your last name']
		},
		displayName: {
			type: String,
			trim: true
		},
		email: {
			type: String,
			trim: true,
			unique: 'testing error message',
			required: 'Please fill in an email',
			lowercase: true,
			default: '',
			validate: [validateLocalStrategyProperty, 'Please fill in your email'],
			match: [/.+\@.+\..+/, 'Please fill a valid email address']
		},
		password: {
			type: String,
			default: '',
			validate: [validateLocalStrategyPassword, 'Password should be longer']
		},

		birthDate: {
			type: Date,
			required: true
		},
		gender: {
			type: [{
				type: String,
				enum: ['male', 'female']
			}],
			required: true,
			lowercase: true,
		},

		salt: {
			type: String
		},
		provider: {
			type: String,
			required: 'Provider is required'
		},
		providerData: {},
		additionalProvidersData: {},
		roles: {
			type: [{
				type: String,
				enum: ['user', 'admin']
			}],
			default: ['user']
		},
		updated: {
			type: Date
		},
		created: {
			type: Date,
			default: Date.now
		},
		/* For reset password */
		resetPasswordToken: {
			type: String
		},
		resetPasswordExpires: {
			type: Date
		}
	});
};
util.inherits(BaseSchema, Schema);

var UserSchema = new BaseSchema();

mongoose.model('User', UserSchema);

module.exports = BaseSchema;
```
But there is an error when launching the application : 
**this.add({
	    ^
TypeError: Cannot read property 'add' of undefined**

**Comment by codydaig** [comment]
@Solidary I'm not familiar with Base Schema's, but it seems that your 'this' isn't in the context you think it is. 
http://mongoosejs.com/docs/plugins.html

**Comment by Solidary** [comment]
The problem is about **this** which is undefined. But I don't why.
I just follow the instructions inheritance on mongoose. Follow this link [Discriminator](http://mongoosejs.com/docs/api.html#model_Model.discriminator) please to see the example.

**Comment by mleanos** [comment]
@Solidary I use this in my meanjs project. It works quite well, and is really easy to implement into this project. `mongoose-schema-extend` isn't actively maintained, however it's a very small library.

https://github.com/briankircho/mongoose-schema-extend

There are pretty straight forward examples at the above link. If you run into any issues, you can reach out to me here or on Gitter & I'll be more than happy to assist. I'll look into your solution a bit more, and see if I can provide some additional insight in case you don't want to go with my suggestion.

**Comment by codydaig** [comment]
@Solidary Any update on this issue? I'm closing, but feel free to reopen if it's still an issue.

**Comment by zeldar** [comment]
@codydaig I opened this issue because I have been trying different solutions to mongoose schema inheritance, but I have a GIST with working discriminators from mongoose for the Articles Module.  There seems to be little working documentation out there for that feature.  There are a few good use cases I believe. 

I'm still working on getting discriminators working on Users.  @codydaig Do you see enough questions to justify the use case for an optional discriminator for a secondary user type in this project?  Is it worth discussing if it is better to create a new model, new controllers, and new services for the second type of user, or will it completely depend on the use case?  

I saw the Admin Dashboard added and that was something I was working on as well.  I like the current implementation of the Admin User, but I'm currently writing an app with a second type of "user" with completely different permissions, not including the admin.  I think this might be a semi-common use case.  Maybe only documentation worthy.
