### ISSUE TITLE
node 4.0 update

### ISSUE THREAD

**Issue by quanphan** [meanjs/mean#902]
I have a error "Segmentation fault: 11" with server.js  when updated node to v4.0. 
How to fix it. 
thanks

**Comment by codydaig** [comment]
@quanphan We have not tested this project with 4.0 yet. The project currently supports 0.10 and 0.12.

**Comment by quanphan** [comment]
Thank @codydaig. So, how to run project currently with Java script ES6

**Comment by codydaig** [comment]
node version 0.12.x has a lot of ES6 support built into it. I'm not sure how much, but I know that it's covered every ES6 use case that I encountered. I have a feeling it's going to take some time before 4.0 is widely adopted because there are a lot of core dependencies that need to support 4.0 before projects can start supporting it. For example, I tried running a much smaller side project of mine on 4.0 and it fails because of an issue in bcrypt.

**Comment by lirantal** [comment]
Node v4.0 was only very recently released, and we didn't yet test that indeed.
We still need to decide on the supported versions.

**Comment by codydaig** [comment]
@lirantal I've got Node 4.0 on a docker container for this project. After I finish some core sub modules for the generator I'll investigate what it will take to make it compatible with 4.0.

**Comment by ilanbiala** [comment]
Let's add 4.0 as a test environment to travis at least. Is there a way to ignore that build's status regarding passing/failing until we get it passing?

**Comment by codydaig** [comment]
I'm not sure, but if there is a way, then I'm down for it.

**Comment by lirantal** [comment]
Yes, there's a way, I'll set it up.
