### ISSUE TITLE
Docs can improve it?

### ISSUE THREAD

**Issue by blueflagbj** [meanjs/mean#915]
Docs can improve it? Difficult for beginners to get started！

**Comment by lirantal** [comment]
@blueflagbj you're right, we should indeed work further on the docs.
any specific sections that seem more important for you than others in terms of priority?

**Comment by zeldar** [comment]
@lirantal I'd be happy to help with the docs for 0.4+ as well.  

I've been using mean.js since 0.3 on multiple projects. 

1.  I can write an easy guide for replacing grunt with gulp, if that is useful.  
2.  I also remove all LESS components for sass-bootstrap.  I remove the LESS watch tasks.  Would this be useful documentation, or does it belong somewhere else?
3.  Feel free to send me suggestions and I will contribute. 

I'll send a pull request once I get one done.

**Comment by codydaig** [comment]
@zeldar #743 is where our documentation ToDo List is. Feel free to pick a task and run with it! As for the other suggestions, I like them I'm just not sure where we'd want to put them. My gut instinct says put them in the WiKi, but @lirantal or @ilanbiala should have a better idea about that.

Thanks! :-D

**Comment by ilanbiala** [comment]
@lirantal any preference between the wiki and gh-pages?

**Comment by lirantal** [comment]
Let's stick with gh-pages for project documentation, it's what we've done so far and is easier to 
collaborate on rather than the wiki.

@zeldar I second @codydaig with regards to viewing our task list for documentation areas in that issue

**Comment by codydaig** [comment]
Closing in favor of #743.
