### ISSUE TITLE
Forcing a build on heroku

### ISSUE THREAD

**Issue by mikepc** [meanjs/mean#960]
When I get push heroku master, everything is successful, but unless I add the build output and run the build command locally and push those files, they don't get built post install.

Could someone who has deployed to heroku help me out getting the build to work?

**Comment by mleanos** [comment]
There's a not so elegant way that I've deployed a staging app to Heroku...

I've modified my package postinstall script to be this: 
`"postinstall": "bower install --config.interactive=false && gulp build"`
I'm using Gulp because I remember having some issues with Grunt, but I think it may have been related to something else. So you should be able to use Grunt instead here.

The build script, will minify your app files (css, and js) and put them into the *public/dist* folder. This will execute while deploying to Heroku. Thus, it puts your build output on the new deployed version of your app.

There's also two settings that I set on Heroku: 
NODE_ENV: production
NPM_CONFIG_PRODUCTION: false

The 2nd setting above, will build the packages dev dependencies. Which isn't the recommended approach, but it's the simplest way that I got it to work & build. The other approach would be to add any dependencies that you need in order for the `build` task to complete.

I've been trying to come up with a better deployment method, but I'm finding it a little difficult. Heroku, is tricky.

**Comment by codydaig** [comment]
@mikepc Did this answer your question?

**Comment by ilanbiala** [comment]
Gitter or Stack Overflow are better forums, please discuss this there.
